// 各歌手在 YouTube Music 的官方藝人頻道與 Wikipedia 條目；slug 用於網址與資料檔名。
// 前端與 Node 抓取腳本共用這份清單，依出道日期（Wikipedia 資訊框的出道日期／出道作發行）排列。
// group：female 女歌手、male 男歌手、group 團體；lang：'tw' 台語歌手（沒寫是華語）。首頁依兩者分頁。
// extraChannelIds：作品分散在其他頻道時一併抓取合併。
// aliases：曲目演出者欄可能出現的其他名字（舊藝名、外語名），用來判斷是不是這位歌手唱的。
// 團體與個人分開計算（出道日期也是各自的）：
//   groups（個人）：演出者含這些團體名的曲目是團體作品，不列入個人
//   members（團體）：演出者只寫團員名、沒有團名的曲目是個人作品，不列入團體
// names：只認這些名字（頻道混了同名的其他歌手時用，例如信的「SHIN」頻道），取代自動產生的名字清單
// cjkOnly：頻道混了同名的外國歌手時，只收中文標題的專輯（B.A.D.）
// photo：頻道照片不對時指定，'wikipedia' 用 Wikipedia 條目主圖，或直接填圖片網址
// releases：頻道混了很多同名歌手時，只收這些專輯（YouTube Music 的 browseId）
// excludeReleases：YouTube Music 把別人的作品標成這位歌手時，排除這些 browseId
// extraReleases：歌手頁與搜尋都撈不到、但確實是他的發行，手動補上 browseId
export const ARTISTS = [
  { slug: 'chi-lu-hsia', group: 'female', lang: 'tw', name: '紀露霞', en: 'Chi Lu-hsia', debut: '1956', channelId: 'UClGlbgq9Gy3mmdEde-ekQeA', wiki: '紀露霞', aliases: ['邱秋英', 'Lu-Hsia Chi', 'Chi Lu-Hsia'] },
  { slug: 'judy-ongg', group: 'female', name: '翁倩玉', en: 'Judy Ongg', debut: '1960', channelId: 'UC9NKMcJmtnmXhsq0RwUEYEw', extraChannelIds: ['UCLQJWIKWHdYbAtkIG6tPJZA'], wiki: '翁倩玉', aliases: ['ジュディ・オング'] },
  { slug: 'fang-jui-o', group: 'female', lang: 'tw', name: '方瑞娥', en: 'Fang Jui-o', debut: '1963', channelId: 'UCcRXkwjaloeWlyMhzL1336w', extraChannelIds: ['UC_woKiIP1D4WkBY6T9ilCVA'], wiki: '方瑞娥' },
  { slug: 'yu-tian', group: 'male', name: '余天', en: 'Yu Tian', debut: '1964', channelId: 'UCqlcj_1M7SndetpNe_Gk0dQ', extraChannelIds: ['UCrLE55dIJegKIoT7Yp8-yow', 'UC2oZGFc-xIcK8b82oFhrw3w', 'UCihP63eW0WzfIRlsEXRdDGQ'], wiki: '余天', aliases: ['余清源'] },
  { slug: 'ouyang-fei-fei', group: 'female', name: '歐陽菲菲', en: 'Ouyang Fei Fei', debut: '1966', channelId: 'UC5nvsmdF62lN570NZdxq84g', wiki: '歐陽菲菲' },
  { slug: 'teresa-teng', group: 'female', name: '鄧麗君', en: 'Teresa Teng', debut: '1967', channelId: 'UCI2cy2lwlzMksxEu63E8Zag', wiki: '鄧麗君', aliases: ['テレサ・テン'] },
  { slug: 'feng-fei-fei', group: 'female', name: '鳳飛飛', en: 'Feng Fei Fei', debut: '1968', channelId: 'UCylxmFpXSfOsnuaOn5NCc1g', wiki: '鳳飛飛' },
  { slug: 'billie', group: 'female', name: '比莉', en: 'Billie Wang', debut: '1968', channelId: 'UCAFAUGv8wEfEmXI3KmJ__0A', extraChannelIds: ['UCY0XLt7Kt9XwVQ8pOsZy93A'], wiki: '比莉', aliases: ['王雪娥', 'Billie Wang', '王雪娥 Billie'] },
  { slug: 'jenny-tseng', group: 'female', name: '甄妮', en: 'Jenny Tseng', debut: '1971', channelId: 'UCqyj20f20wX3ewzRuW2E2_Q', wiki: '甄妮', aliases: ['Zhen Ni', '甄淑詩'] },
  { slug: 'fei-yu-ching', group: 'male', name: '費玉清', en: 'Fei Yu-ching', debut: '1972', channelId: 'UCz8-WnBsFqpsWquij7_AINg', wiki: '費玉清' },
  { slug: 'chen-ying-git', group: 'female', lang: 'tw', name: '陳盈潔', en: 'Chen Ying-git', debut: '1972', channelId: 'UCjeq0XOaAcqYt5IZ3w1oMCA', wiki: '陳盈潔' },
  { slug: 'sarah-chen', group: 'female', name: '陳淑樺', en: 'Sarah Chen', debut: '1973', channelId: 'UCCmIJng9-OXs9Ax5P4-m8UA', wiki: '陳淑樺' },
  { slug: 'pai-ping-ping', group: 'female', lang: 'tw', name: '白冰冰', en: 'Pai Ping-ping', debut: '1973', channelId: 'UCtr4s78e4kL_oC93UTm8n0Q', wiki: '白冰冰' },
  { slug: 'sylvia-chang', group: 'female', name: '張艾嘉', en: 'Sylvia Chang', debut: '1973', channelId: 'UCzPfHHyh46cCfyyzpR9b2Jg', wiki: '張艾嘉', aliases: ['张艾嘉'], photo: 'wikipedia' },
  { slug: 'tracy-huang', group: 'female', name: '黃鶯鶯', en: 'Tracy Huang', debut: '1974', channelId: 'UCmQWBgcJyjLBdoF428F6y1A', aliases: ['黃露儀', '黄露仪', 'Tracy黃露儀'], wiki: '黃鶯鶯' },
  { slug: 'liu-wen-cheng', group: 'male', name: '劉文正', en: 'Liu Wen-cheng', debut: '1975', channelId: 'UC3IfLD_N7AFxUjc8I0t2D5g', wiki: '劉文正' },
  { slug: 'eric-hung', group: 'male', lang: 'tw', name: '洪榮宏', en: 'Eric Hung', debut: '1977', channelId: 'UCdLRI11OrDEqaAszBH9VytQ', wiki: '洪榮宏' },
  { slug: 'wang-chih-lei', group: 'female', name: '王芷蕾', en: 'Wang Chih-lei', debut: '1977', channelId: 'UCl1XB7-00b9cTp2VWt3KKOw', extraChannelIds: ['UC8ZCHCLsjA5kYtoecilJMPg'], wiki: '王芷蕾' },
  { slug: 'chyi-yu', group: 'female', name: '齊豫', en: 'Chyi Yu', debut: '1978', channelId: 'UCN82-y6I2oH9Tw8LaPw2sYg', wiki: '齊豫' },
  { slug: 'lin-shu-rong', group: 'female', name: '林淑容', en: 'Lin Shu-rong', debut: '1978', channelId: 'UC8_Kh4QgXCYwxcLj_d_F_mA', wiki: '林淑容' },
  { slug: 'chen-ming-chang', group: 'male', lang: 'tw', name: '陳明章', en: 'Chen Ming Chang', debut: '1978', channelId: 'UCNgWDy1xigmgWVLH0ON6ymQ', extraChannelIds: ['UC4TOxyqvwSG0fFapg2tj68g'], wiki: '陳明章', aliases: ['Cheng Minjang', 'Chen Mingchang'] },
  { slug: 'tsai-chin', group: 'female', name: '蔡琴', en: 'Tsai Chin', debut: '1979', channelId: 'UCiqpapiuXXw7y0BdBXL-hzA', excludeReleases: ['MPREb_llQhhK7Pued'], wiki: '蔡琴', aliases: ['Cai Qin'] },
  { slug: 'yvonne-cheng', group: 'female', name: '鄭怡', en: 'Yvonne Cheng', debut: '1979', channelId: 'UCuvGX4pEScIUjZ4fuvFraaw', wiki: '鄭怡' },
  { slug: 'michelle-pan', group: 'female', name: '潘越雲', en: 'Michelle Pan', debut: '1979-10', channelId: 'UCCaauu_jc2rhNsx66SYjTKQ', wiki: '潘越雲' },
  { slug: 'sally-yeh', group: 'female', name: '葉蒨文', en: 'Sally Yeh', debut: '1980', channelId: 'UChzDLyeh1Fvy6UPdA-VdE3A', wiki: '葉蒨文', aliases: ['叶蒨文', '葉倩文', '叶倩文'] },
  { slug: 'tsai-chiu-feng', group: 'female', lang: 'tw', name: '蔡秋鳳', en: 'Carris', debut: '1980', channelId: 'UCZDwO_d1nRdFrZNowpNBnVw', wiki: '蔡秋鳳' },
  { slug: 'michael-huang', group: 'male', name: '黃仲崑', en: 'Michael Huang', debut: '1980-07', channelId: 'UCUPUYT5g00Tk1v152A4gpfQ', wiki: '黃仲崑' },
  { slug: 'chyi-chin', group: 'male', name: '齊秦', en: 'Chyi Chin', debut: '1981', channelId: 'UCXAFPuHD3vHw9agvXeY948A', wiki: '齊秦' },
  { slug: 'chen-hsiao-hsia', group: 'female', name: '陳小霞', en: 'Chen Hsiao-hsia', debut: '1981', channelId: 'UCy-kBHDxcbI557rchz5mqcg', wiki: '陳小霞' },
  { slug: 'chiuchiu', group: 'group', name: '丘丘合唱團', en: '', debut: '1981', channelId: 'UCgU9GPDJEKbwKakttjyWn-w', wiki: '丘丘合唱團', members: ['邱晨', '金智娟', '林俊修', '李應錄'] },
  { slug: 'jody-chiang', group: 'female', lang: 'tw', name: '江蕙', en: 'Jody Chiang', debut: '1981-04', channelId: 'UCJHd5tIDLb6YuNg3L_Ad15A', wiki: '江蕙' },
  { slug: 'anita-mui', group: 'female', name: '梅艷芳', en: 'Anita Mui', debut: '1982', channelId: 'UCllyCYlWEeBeZ4v3kNqz0AA', wiki: '梅艷芳' },
  { slug: 'lin-hui-ping', group: 'female', name: '林慧萍', en: 'Lin Hui-ping', debut: '1982', channelId: 'UCNDJh_nCTv5tC0udzvIqMxg', wiki: '林慧萍' },
  { slug: 'lo-ta-yu', group: 'male', name: '羅大佑', en: 'Lo Ta-yu', debut: '1982', channelId: 'UCLw1fD-M2rKFBM9zGXfUwFA', excludeReleases: ['MPREb_y2f3qNHJduw'], wiki: '羅大佑', groups: ['縱貫線'] },
  { slug: 'tsai-chen-nan', group: 'male', lang: 'tw', name: '蔡振南', en: 'Tsai Chen-nan', debut: '1982', channelId: 'UC27lmPfn0fNqVfWeSFnOPpQ', wiki: '蔡振南' },
  { slug: 'cheng-gin-yi', group: 'male', lang: 'tw', name: '鄭進一', en: 'Cheng Gin Yi', debut: '1982', channelId: 'UCE6Fd46DDEfAcg3oZoKQ4fg', extraChannelIds: ['UCxLjyt1TCTWCeH2SOFeKHIg', 'UCJ4rmXOajY5SMwiY8b_XOdw'], wiki: '鄭進一', aliases: ['鄭俊義'] },
  { slug: 'julie-sue', group: 'female', name: '蘇芮', en: 'Julie Sue', debut: '1983', channelId: 'UC7GaEq4YeIndQAmWZGCp1jA', wiki: '蘇芮', aliases: ['Julie Su'] },
  { slug: 'eric-moo', group: 'male', name: '巫啟賢', en: 'Eric Moo', debut: '1983', channelId: 'UC9lm7Q16zOCSB5zSy1WKmCA', wiki: '巫啟賢' },
  { slug: 'johnnybug-chen', group: 'male', name: '小蟲', en: 'Johnnybug Chen', debut: '1983', channelId: 'UCfDH7toJB8KCuM4GOWhXsWg', wiki: '陳煥昌', aliases: ['陳煥昌', '小虫'] },
  { slug: 'chang-hsiu-ching', group: 'female', lang: 'tw', name: '張秀卿', en: 'Chang Hsiu-ching', debut: '1984', channelId: 'UCumI8mnswd5bneJE01ZbgkA', wiki: '張秀卿' },
  { slug: 'stella-chang', group: 'female', name: '張清芳', en: 'Stella Chang', debut: '1984', channelId: 'UCgqKZd77uZDWKtZYViztZng', wiki: '張清芳' },
  { slug: 'chiang-yu-heng', group: 'male', name: '姜育恒', en: 'Chiang Yu-heng', debut: '1984', channelId: 'UC-Sgwn5dDZQnaxmOf9xVBZQ', wiki: '姜育恒' },
  { slug: 'chen-hsiao-yun', group: 'female', lang: 'tw', name: '陳小雲', en: 'Chen Hsiao-yun', debut: '1984', channelId: 'UCC6LQEHltSXqmgcHXBMN2oA', wiki: '陳小雲', aliases: ['陈小云', '陳小云'] },
  { slug: 'cheng-hua-chuan', group: 'female', name: '鄭華娟', en: 'Cheng Hua-chuan', debut: '1984', channelId: 'UCfxHhGJHlMfQXawUdwwE0kw', extraChannelIds: ['UClKu6WVbngfrHWRZ_2C_lQw'], wiki: '鄭華娟' },
  { slug: 'ann-hsu', group: 'female', name: '許景淳', en: 'Ann Hsu', debut: '1984', channelId: 'UCL10i4M5aaR7l_maC2Q0ZIw', wiki: '許景淳' },
  { slug: 'lan-hsin-mei', group: 'female', name: '藍心湄', en: 'Pauline Lan', debut: '1984', channelId: 'UCZ0tKFweUIY47AWEvsEw_FQ', wiki: '藍心湄', aliases: ['蓝心湄', 'Xin Mei Lan'] },
  { slug: 'cui-jian', group: 'male', name: '崔健', en: 'Cui Jian', debut: '1984', channelId: 'UCFr2ApO5mByAP7uT0uLEx8g', wiki: '崔健' },
  { slug: 'wen-zhang', group: 'male', name: '文章', en: 'Wen Zhang', debut: '1984', channelId: 'UCS-ad14dz7qmrrRdOdjlbdQ', wiki: '文章 (歌手)', aliases: ['黃文章'] },
  { slug: 'alex-to', group: 'male', name: '杜德偉', en: 'Alex To', debut: '1984-11-02', channelId: 'UCLrRf6ykvhzRJwZP2cqxYBA', wiki: '杜德偉' },
  { slug: 'sandy-lam', group: 'female', name: '林憶蓮', en: 'Sandy Lam', debut: '1985', channelId: 'UChwNyOQOnJ6n1H5EDnkpXhw', wiki: '林憶蓮' },
  { slug: 'andy-lau', group: 'male', name: '劉德華', en: 'Andy Lau', debut: '1985', channelId: 'UCoyRETheGZlMXL-Jx83UsHQ', wiki: '劉德華' },
  { slug: 'angus-tung', group: 'male', name: '童安格', en: 'Angus Tung', debut: '1985', channelId: 'UCHELx82CTElRgL6eU8WFNfA', wiki: '童安格' },
  { slug: 'lily-duo', group: 'group', name: '大小百合', en: '', debut: '1985', channelId: 'UCForA53W3XrX3HaW-C7Ws4w', wiki: '百合二重唱', aliases: ['百合二重唱', '大小百合'] },
  { slug: 'lo-shih-feng', group: 'male', lang: 'tw', name: '羅時豐', en: 'Daniel Lo', debut: '1985', channelId: 'UCjxzPiYWzahwqPanmrqt1Xw', extraChannelIds: ['UCo5_FYfpP4kPLeXbofFg_ZQ', 'UCQiFn6sMOkW_K4akRAhCvKw'], wiki: '羅時豐', aliases: ['Luo Shi Feng', '羅時丰'] },
  { slug: 'vivian-chow', group: 'female', name: '周慧敏', en: 'Vivian Chow', debut: '1985', channelId: 'UCLH19O6Nu0c5AcO0ABlnHJw', wiki: '周慧敏' },
  { slug: 'jacky-cheung', group: 'male', name: '張學友', en: 'Jacky Cheung', debut: '1985-01-01', channelId: 'UCSdxcm9HfRCubJBhW92QoFQ', wiki: '張學友' },
  { slug: 'winnie-hsin', group: 'female', name: '辛曉琪', en: 'Winnie Hsin', debut: '1986', channelId: 'UCmC8dCKfO3ZZtxYNvkadmxA', wiki: '辛曉琪' },
  { slug: 'jonathan-lee', group: 'male', name: '李宗盛', en: 'Jonathan Lee', debut: '1986', channelId: 'UCSypPS59F8OUy_abhYo0viQ', wiki: '李宗盛', groups: ['縱貫線'] },
  { slug: 'harlem-yu', group: 'male', name: '庾澄慶', en: 'Harlem Yu', debut: '1986', channelId: 'UC93ziw5QSSY8Gyacz-YGTlA', wiki: '庾澄慶' },
  { slug: 'johnny-yin', group: 'male', name: '殷正洋', en: 'Johnny Yin', debut: '1986', channelId: 'UCKZDmHQN0SDozH0uBbBNWuA', wiki: '殷正洋', extraChannelIds: ['UCxYVZk894dNAXQ8KZHhI1lw'] },
  { slug: 'fan-ren-duo', group: 'group', name: '凡人二重唱', en: '', debut: '1986', channelId: 'UCsm3f9M2t2EaYF_CNeIny0Q', extraChannelIds: ['UCb5pr2NuvpNs78q60sMbPJw'], wiki: '凡人二重唱', aliases: ['凡人'], members: ['莫凡', '袁惟仁'] },
  { slug: 'tang-na', group: 'female', name: '坣娜', en: 'Tang Na', debut: '1986', channelId: 'UC3BOwUHqnArt1dpYRrdEMJg', wiki: '坣娜', aliases: ['唐娜', 'Na Na Tang'] },
  { slug: 'linda-lee', group: 'female', name: '李翊君', en: 'Linda Lee', debut: '1986', channelId: 'UCzozJTzoyp5PJjN3er7P7OQ', wiki: '李翊君', aliases: ['李華苓'] },
  { slug: 'kay-huang', group: 'female', name: '黃韻玲', en: 'Kay Huang', debut: '1986', channelId: 'UCV1lfFSgALN728afX6Zzzaw', extraChannelIds: ['UCjLfL27GLdv6lQBC3iL3PtA'], wiki: '黃韻玲', aliases: ['Kay Huang'] },
  { slug: 'yu-tai-yan', group: 'female', name: '于台煙', en: 'Yu Tai-yan', debut: '1986', channelId: 'UC_x5Jzq_cgW4uWGeFJeADeA', wiki: '于台煙', aliases: ['于台烟'] },
  { slug: 'sky-wu', group: 'male', name: '伍思凱', en: 'Sky Wu', debut: '1986-09', channelId: 'UCJ5SvoAXx-eyoAX-g1imSjg', wiki: '伍思凱' },
  { slug: 'huang-yee-ling', group: 'female', lang: 'tw', name: '黃乙玲', en: 'Huang Yee-ling', debut: '1987', channelId: 'UCvAECH-laxIYOFxLmeRjcjA', wiki: '黃乙玲' },
  { slug: 'jason-wang', group: 'male', lang: 'tw', name: '王識賢', en: 'Jason Wang', debut: '1987', channelId: 'UC1tCFFD3gEPpbEQSwJpycEw', extraChannelIds: ['UC_MCbsdZMlp36MMgBODKxeA', 'UCOVM9Jfn8xNpW25PhxcVLMg'], wiki: '王識賢' },
  { slug: 'wakin-chau', group: 'male', name: '周華健', en: 'Wakin Chau', debut: '1987', channelId: 'UC02VMzK8EMIDTqDeR7wLAig', wiki: '周華健', groups: ['縱貫線'] },
  { slug: 'annie-yi', group: 'female', name: '伊能靜', en: 'Annie Yi', debut: '1987', channelId: 'UCMKArTZwfkqlVRKaruMDvhw', extraChannelIds: ['UC5HY4dsAlWlWLt_hag64tmw'], wiki: '伊能靜', aliases: ['伊能静', '安妮一世', 'Annie Yi'] },
  { slug: 'a-chi-tsai', group: 'male', lang: 'tw', name: '阿吉仔', en: 'A-Chi', debut: '1987', channelId: 'UC1AgjmV4urpzWXQGzJ1zCCw', extraChannelIds: ['UCjBaSJrQBvYa4KYMtuKdWbQ', 'UCcUApEzRFj5M0Sh8BJr5MBg'], wiki: '阿吉仔', aliases: ['林清吉'] },
  { slug: 'fang-wen-lin', group: 'female', name: '方文琳', en: 'Fang Wen-lin', debut: '1987-04', channelId: 'UCBOs2fVHFqD7YgylCIkoDkg', extraChannelIds: ['UCZdLFML9FrPdBKmDwP82tiw'], wiki: '方文琳' },
  { slug: 'dave-wang', group: 'male', name: '王傑', en: 'Dave Wang', debut: '1987-12', channelId: 'UCHJqqcu2FYNqCrBRBbYAAkA', wiki: '王傑 (1962年)', aliases: ['王杰'] },
  { slug: 'cyndi-chao', group: 'female', name: '趙詠華', en: 'Cyndi Chao', debut: '1988', channelId: 'UCSCwNNMlx6buDMAvK4K6PGA', wiki: '趙詠華', aliases: ['Cyndi Zhao'] },
  { slug: 'jeff-chang', group: 'male', name: '張信哲', en: 'Jeff Chang', debut: '1988', channelId: 'UC37Uu5Sk6MCBFJNSDPNbZ5w', aliases: ['傑夫·張', '傑夫張'], wiki: '張信哲' },
  { slug: 'bobby-chen', group: 'male', name: '陳昇', en: 'Bobby Chen', debut: '1988', channelId: 'UC4lfQ2v3iBxHmYzYRKURyOQ', wiki: '陳昇', groups: ['新寶島康樂隊'] },
  { slug: 'chao-chuan', group: 'male', name: '趙傳', en: 'Chao Chuan', debut: '1988', channelId: 'UC-dJiwRh629gT2w1poIPFdw', wiki: '趙傳' },
  { slug: 'chen-lei', group: 'male', lang: 'tw', name: '陳雷', en: 'Chen Lei', debut: '1988', channelId: 'UCT_Zy8GiekHfKUWYaXrVIHg', wiki: '陳雷 (歌手)' },
  { slug: 'david-wong', group: 'male', name: '黃大煒', en: 'David Wong', debut: '1988', channelId: 'UCW5WOfVE_9n-mZUKvj9IGJA', wiki: '黃大煒' },
  { slug: 'tom-chang', group: 'male', name: '張雨生', en: 'Tom Chang', debut: '1988', channelId: 'UC5IOk7upUslbdPuMj1DU-WA', wiki: '張雨生' },
  { slug: 'little-tigers', group: 'group', name: '小虎隊', en: 'The Little Tigers', debut: '1988', channelId: 'UCJVY7dg31Qk35UJKowIVttg', wiki: '小虎隊', aliases: ['The Little Tigers'], members: ['吳奇隆', '蘇有朋', '陳志朋', '林立洋'] },
  { slug: 'na-ying', group: 'female', name: '那英', en: 'Na Ying', debut: '1988', channelId: 'UC7tVAVl0FfQ4ylidGciMJZQ', wiki: '那英' },
  { slug: 'fang-chi-wei', group: 'female', name: '方季惟', en: 'Fang Chi-wei', debut: '1988', channelId: 'UCRH6-9GABaRk4XXaTHTzCmQ', wiki: '方季韋', aliases: ['方季韋'] },
  { slug: 'huang-shu-chun', group: 'male', name: '黃舒駿', en: 'Huang Shu-chun', debut: '1988', channelId: 'UCqhhS-3zaGhbIwsb0izUNXQ', extraChannelIds: ['UCkZV2RVtSKQ7_pQ_guGfduA'], wiki: '黃舒駿', aliases: ['黄舒骏', 'Shu Jun Huang'] },
  { slug: 'tseng-hsin-mei', group: 'female', lang: 'tw', name: '曾心梅', en: 'Tseng Hsin-mei', debut: '1988', channelId: 'UCSw5-tznXGAaPQGAJENwHtQ', extraChannelIds: ['UC8YkQmqgZs4A2G9-s4mhQ-g'], wiki: '曾心梅', aliases: ['曾小萍'] },
  { slug: 'samuel-tai', group: 'male', name: '邰正宵', en: 'Samuel Tai', debut: '1988', channelId: 'UCArSd4-QPn3j-zlYNtcnjYA', wiki: '邰正宵', aliases: ['邰正霄'] },
  { slug: 'anna-wang', group: 'female', lang: 'tw', name: '王瑞霞', en: 'Anna Wang', debut: '1988', channelId: 'UCwdTrbKg8W6mBjuOs64sfTQ', wiki: '王瑞霞 (歌手)' },
  { slug: 'yang-tsung-hsien', group: 'male', lang: 'tw', name: '楊宗憲', en: 'Yang Tsung-hsien', debut: '1988', channelId: 'UCRkUyfuTBU59dUOlnopIrcQ', wiki: '楊宗憲' },
  { slug: 'yo-huan', group: 'group', name: '憂歡派對', en: '', debut: '1988', channelId: 'UCOb0Eckgm-ZH8Y4WN_3EFMw', wiki: '憂歡派對', aliases: ['忧欢派对'], members: ['蔡雨倫', '于佳卉'] },
  { slug: 'andy-hui', group: 'male', name: '許志安', en: 'Andy Hui', debut: '1988-05-05', channelId: 'UC3m7HOzdx2VWyvkCT5Ti4pg', wiki: '許志安', aliases: ['许志安'] },
  { slug: 'faye-wong', group: 'female', name: '王菲', en: 'Faye Wong', debut: '1989', channelId: 'UCnAmvOfJxmcMd5q48BEIuPQ', wiki: '王菲', aliases: ['王靖雯', 'Shirley Wong'] },
  { slug: 'kuo-heng-chi', group: 'male', name: '郭子', en: 'Kuo Heng-Chi', debut: '1989', channelId: 'UCAPSacD-z0BrzC4ib6aoq3w', extraChannelIds: ['UCJvKttuOdmo0ribnORxfNwg', 'UC4ZZgiyCT6Bm2ZIYfUqVVnA'], wiki: '郭蘅祈' },
  { slug: 'william-so', group: 'male', name: '蘇永康', en: 'William So', debut: '1989', channelId: 'UC2R81DoE9-OQCb38YpeimZw', wiki: '蘇永康' },
  { slug: 'steve-chou', group: 'male', name: '周傳雄', en: 'Steve Chou', debut: '1989', channelId: 'UCGh_v5aXDXCanMfU6O31JXw', wiki: '周傳雄', aliases: ['周传雄', '小剛'] },
  { slug: 'chang-hung-liang', group: 'male', name: '張洪量', en: 'Chang Hung-liang', debut: '1989', channelId: 'UCbps6I6U8foTtJiBFctZxIw', extraChannelIds: ['UCFYK1txYf7kL0JPiur-tQWg'], wiki: '張洪量', aliases: ['张洪量'] },
  { slug: 'jonathan-chang', group: 'male', name: '張克帆', en: 'Jonathan Chang', debut: '1989', channelId: 'UCvaA7Hkic0Qjw2GRHu4ICxw', extraChannelIds: ['UCi24_NhbAB3doe0AC7_eXQw', 'UC036WgkUNYNMFMKBHmaURtQ'], wiki: '張克帆', groups: ['紅孩兒'] },
  { slug: 'chris-yu', group: 'male', name: '游鴻明', en: 'Chris Yu', debut: '1989', channelId: 'UCr37SMBLagyVJhne9eC0BEg', aliases: ['游鸿明'], wiki: '游鴻明' },
  { slug: 'the-boys', group: 'group', name: '紅孩兒', en: 'The Boys', debut: '1989', channelId: 'UC_X9KGdr0gW0c3esnusWBTA', wiki: '紅孩兒 (團體)', aliases: ['红孩兒', 'Red Hot Boys'], members: ['馬國賢', '湯俊霈', '張洛君', '張克帆', '王海輪', '韓志杰', '沈依智'] },
  { slug: 'oriental-express', group: 'group', name: '東方快車', en: 'Oriental Express', debut: '1989', channelId: 'UC6fiiESHOP7xIhRxA0pA6fw', wiki: '搖滾東方', aliases: ['東方快車合唱團', '搖滾東方'] },
  { slug: 'wan-fang', group: 'female', name: '萬芳', en: 'Wan Fang', debut: '1990', channelId: 'UC7W9UR7f56ZcmN-fGg4Pvww', wiki: '萬芳' },
  { slug: 'sammi-cheng', group: 'female', name: '鄭秀文', en: 'Sammi Cheng', debut: '1990', channelId: 'UCM8Xiz5yxDCdsP_o6ihVcaA', wiki: '鄭秀文' },
  { slug: 'leon-lai', group: 'male', name: '黎明', en: 'Leon Lai', debut: '1990', channelId: 'UCH5hUc-wpv63XKUOEWziVWQ', wiki: '黎明' },
  { slug: 'aaron-kwok', group: 'male', name: '郭富城', en: 'Aaron Kwok', debut: '1990', channelId: 'UCRKMiqk5_omDtmZvWUQFxGQ', wiki: '郭富城' },
  { slug: 'richie-jen', group: 'male', name: '任賢齊', en: 'Richie Jen', debut: '1990', channelId: 'UCXjVKjtAwUS4ehpCvQtvNNg', wiki: '任賢齊' },
  { slug: 'matilda-tao', group: 'female', name: '陶晶瑩', en: 'Matilda Tao', debut: '1990', channelId: 'UCvQkRDQQyKsJGsAriOucV5w', extraChannelIds: ['UCINirz-ZCkwLrPhWs6Pv5rg'], wiki: '陶晶瑩', aliases: ['陶晶莹', '陶子'] },
  { slug: 'vivian-hsu', group: 'female', name: '徐若瑄', en: 'Vivian Hsu', debut: '1990', channelId: 'UCN7jqt1SWF655-nYqQE6QRQ', wiki: '徐若瑄', aliases: ['ビビアン・スー'], groups: ['少女隊', 'Black Biscuits'] },
  { slug: 'mai-meng', group: 'female', name: '孟庭葦', en: 'Mai Meng', debut: '1990', channelId: 'UC0AQ-H8y_EJmJfRPtFxb5GA', wiki: '孟庭葦', aliases: ['孟庭苇'] },
  { slug: 'jeannie-hsieh', group: 'female', lang: 'tw', name: '謝金燕', en: 'Jeannie Hsieh', debut: '1990', channelId: 'UCBmHXHfpvHtcHitnT-nk62w', wiki: '謝金燕', aliases: ['謝宜庭'] },
  { slug: 'lim-giong', group: 'male', lang: 'tw', name: '林強', en: 'Lim Giong', debut: '1990', channelId: 'UCQ9_tPUyGAMswd8T9zscW2A', wiki: '林強 (1964年)', aliases: ['林志峰'] },
  { slug: 'cass-phang', group: 'female', name: '彭羚', en: 'Cass Phang', debut: '1990', channelId: 'UCiMazTfa3pxHa-Gt7Sw5P7Q', wiki: '彭羚', aliases: ['彭映盈'] },
  { slug: 'tarcy-su', group: 'female', name: '蘇慧倫', en: 'Tarcy Su', debut: '1990-03', channelId: 'UCuzREF7riRhr2BWRqEBcjBA', wiki: '蘇慧倫' },
  { slug: 'huang-pin-yuan', group: 'male', name: '黃品源', en: 'Huang Pin-yuan', debut: '1990-04', channelId: 'UCTiq0eqZOh_zgtfXc10JTxQ', wiki: '黃品源', aliases: ['黄品源'] },
  { slug: 'tiger-huang', group: 'female', name: '黃小琥', en: 'Tiger Huang', debut: '1990-08', channelId: 'UCV6FKRsG3xal52heBj_XWkA', wiki: '黃小琥' },
  { slug: 'nanfang-duo', group: 'group', name: '南方二重唱', en: '', debut: '1991', channelId: 'UCGq2qkDdWVR2WYRBC575MZA', wiki: '南方二重唱', members: ['閻宗玉', '林明樺'] },
  { slug: 'terry-lin', group: 'male', name: '林志炫', en: 'Terry Lin', debut: '1991', channelId: 'UCtIx9a1kI_VQL0hsSV760jw', wiki: '林志炫', groups: ['優客李林'] },
  { slug: 'tsai-hsiao-hu', group: 'male', lang: 'tw', name: '蔡小虎', en: 'Tsai Hsiao-hu', debut: '1991', channelId: 'UCyzH-h6lT8aBph0HaaOg3Bw', wiki: '蔡小虎', aliases: ['蔡金虎'] },
  { slug: 'yuke-lilin', group: 'group', name: '優客李林', en: '', debut: '1991', channelId: 'UC-8TqXu0CBeR6wP-dMaAGVA', aliases: ['Ukulele', 'UkuLele'], wiki: '優客李林', members: ['林志炫', '李驥'] },
  { slug: 'pigheadskin', group: 'male', lang: 'tw', name: '豬頭皮', en: 'Pigheadskin', debut: '1991-05-20', channelId: 'UCRaPTvBgwDSiti-Hfag2qKQ', wiki: '朱約信', aliases: ['朱約信', '朱頭皮', '豬頭皮(朱約信)'] },
  { slug: 'wu-bai', group: 'male', name: '伍佰', en: 'Wu Bai', debut: '1992', channelId: 'UC4caKr9lsFefEUqb_dmpEvA', wiki: '伍佰', aliases: ['伍佰 & China Blue', 'Wu Bai & China Blue', '吳俊霖'] },
  { slug: 'michael-shih', group: 'male', lang: 'tw', name: '施文彬', en: 'Michael Shih', debut: '1992', channelId: 'UCmdxlN0Fe-7f634tS9VDU2w', wiki: '施文彬' },
  { slug: 'new-formosa', group: 'group', lang: 'tw', name: '新寶島康樂隊', en: 'New Formosa Band', debut: '1992', channelId: 'UCdXwSBaUUPejQCZZMLEtP1A', wiki: '新寶島康樂隊', aliases: ['新宝岛康乐队', 'New Formosa Entertainment Troupe'], members: ['陳昇', '黃連煜', '阿Von', '陳世隆'] },
  { slug: 'roger-wang', group: 'male', lang: 'tw', name: '王中平', en: 'Roger Wang', debut: '1992', channelId: 'UCOIbaak9p8Z4wiVdYSlBqmg', extraChannelIds: ['UCQ4-oyBukPlw4FADymzwqZg'], wiki: '王中平', aliases: ['韓志偉'] },
  { slug: 'jimmy-lin', group: 'male', name: '林志穎', en: 'Jimmy Lin', debut: '1992', channelId: 'UCmlCqkp2373HG9GFWWmNbaQ', wiki: '林志穎' },
  { slug: 'karen-mok', group: 'female', name: '莫文蔚', en: 'Karen Mok', debut: '1993', channelId: 'UChrwddvlCf1df9skygWPA6g', wiki: '莫文蔚' },
  { slug: 'zhang-yu', group: 'male', name: '張宇', en: 'Zhang Yu', debut: '1993', channelId: 'UCEbTPcxFJ_fc6dOOBn2fFFg', wiki: '張宇' },
  { slug: 'eric-suen', group: 'male', name: '孫耀威', en: 'Eric Suen', debut: '1993', channelId: 'UCegmtOe7_nNtdNFv91YDCJw', wiki: '孫耀威' },
  { slug: 'wallace-chung', group: 'male', name: '鍾漢良', en: 'Wallace Chung', debut: '1993', channelId: 'UC6Biu1lnIXK1ErMAT1AB76w', wiki: '鍾漢良', aliases: ['鐘漢良'] },
  { slug: 'mindy-quah', group: 'female', name: '柯以敏', en: 'Mindy Quah', debut: '1993', channelId: 'UCnAq_a_2u7GrczgNw74Yb3w', wiki: '柯以敏' },
  { slug: 'chang-chen-yue', group: 'male', name: '張震嶽', en: 'Chang Chen-yue', debut: '1993-07-01', channelId: 'UCiQZhrWSEiWdoHwPJgAon4A', wiki: '張震嶽', groups: ['縱貫線'], aliases: ['张震岳', 'Ayal Komod', 'A-Yue'] },
  { slug: 'kit-chan', group: 'female', name: '陳潔儀', en: 'Kit Chan', debut: '1993-10', channelId: 'UCLSP2UDrV_eQwVRMNGi5HAw', extraChannelIds: ['UCslMhK8rYXLVVTJRF-fH0hA'], wiki: '陳潔儀', aliases: ['陈洁仪'] },
  { slug: 'mavis-hee', group: 'female', name: '許美靜', en: 'Mavis Hee', debut: '1994', channelId: 'UCHl4oR3WDrHi49L2M6m33MA', wiki: '許美靜' },
  { slug: 'sos', group: 'group', name: 'SOS', en: '大S＋小S', debut: '1994', channelId: 'UCxTAx0w8DJfvd0bjV-yF0HQ', wiki: 'ASOS', aliases: ['ASOS', 'S.O.S', 'SOS (大S+小S)'], members: ['徐熙媛', '徐熙娣', 'Barbie Hsu', 'Dee Hsu'] },
  { slug: 'sandee-chan', group: 'female', name: '陳珊妮', en: 'Sandee Chan', debut: '1994', channelId: 'UCUXXjp6SaJb0gT3NQH3d03Q', wiki: '陳珊妮', aliases: ['陈珊妮'] },
  { slug: 'coco-lee', group: 'female', name: '李玟', en: 'CoCo Lee', debut: '1994-06', channelId: 'UCVzDS3qH_E2ooA7AimOrzHQ', wiki: '李玟' },
  { slug: 'rene-liu', group: 'female', name: '劉若英', en: 'Rene Liu', debut: '1995', channelId: 'UCWY-I1axwr3X9YiouSwHf5Q', wiki: '劉若英' },
  { slug: 'mavis-fan', group: 'female', name: '范曉萱', en: 'Mavis Fan', debut: '1995', channelId: 'UCpCPwuMLFLFAWdHE3RWFjqg', wiki: '范曉萱' },
  { slug: 'leehom-wang', group: 'male', name: '王力宏', en: 'Wang Leehom', debut: '1995', channelId: 'UCSirtpIlKNCvnrTN4i0GFvw', wiki: '王力宏', aliases: ['Leehom Wang'] },
  { slug: 'eason-chan', group: 'male', name: '陳奕迅', en: 'Eason Chan', debut: '1995', channelId: 'UC2rCynaFhWz7MeRoqJLvcow', wiki: '陳奕迅' },
  { slug: 'chthonic', group: 'group', lang: 'tw', name: '閃靈', en: 'Chthonic', debut: '1995', channelId: 'UCSIzci_QRVzp6f1m3v3CMUw', wiki: '閃靈樂團', aliases: ['閃靈樂團', 'CHTHONIC'], members: ['林昶佐', '葉湘怡', '劉笙彙', '高嘉嶸', '汪子驤', 'Freddy', 'Doris Yeh'] },
  { slug: 'michael-victor', group: 'group', name: '無印良品', en: 'Michael & Victor', debut: '1995', channelId: 'UCxU_PF9JbrkliBEo58eGZIw', wiki: '無印良品 (樂團)', aliases: ['光良品冠'], members: ['光良', '品冠', 'Michael Wong', 'Victor Wong'] },
  { slug: 'kelly-chen', group: 'female', name: '陳慧琳', en: 'Kelly Chen', debut: '1995', channelId: 'UCQFTe1obSoLmWiTbyx2wfkA', wiki: '陳慧琳', aliases: ['陈慧琳'] },
  { slug: 'may-sun', group: 'female', lang: 'tw', name: '孫淑媚', en: 'May Sun', debut: '1995', channelId: 'UC2T8pvxEjmmZag8oL9eNGMA', extraChannelIds: ['UC1q9hUU3J6e0qGrKNFw0eRA'], wiki: '孫淑媚', aliases: ['孫向晴'] },
  { slug: 'su-ming-yuan', group: 'male', lang: 'tw', name: '蘇明淵', en: 'Justin Su', debut: '1995-05', channelId: 'UCOHfYkEfs3qF8NYkzAdmoUw', wiki: '蘇明淵' },
  { slug: 'valen-hsu', group: 'female', name: '許茹芸', en: 'Valen Hsu', debut: '1995-06', channelId: 'UCZgpCUQ69DOR8OUKAxD8exw', extraReleases: ['MPREb_i3AObzwLRwe'], wiki: '許茹芸' },
  { slug: 'daniel-chan', group: 'male', name: '陳曉東', en: 'Daniel Chan', debut: '1995-12-01', channelId: 'UC0MsG_EpoTYroJTVQKFRJEw', wiki: '陳曉東 (藝人)', aliases: ['陈晓东'] },
  { slug: 'julia-peng', group: 'female', name: '彭佳慧', en: 'Julia Peng', debut: '1996', channelId: 'UC1tBiwuyXgWNLWiUpx53TRA', wiki: '彭佳慧' },
  { slug: 'gigi-leung', group: 'female', name: '梁詠琪', en: 'Gigi Leung', debut: '1996', channelId: 'UC_yk6-0jRw__Ys5cakYotcg', wiki: '梁詠琪' },
  { slug: 'denise-ho', group: 'female', name: '何韻詩', en: 'Denise Ho', debut: '1996', channelId: 'UCq6bV8xawEbYLj7cDTP7iNw', wiki: '何韻詩', aliases: ['何韵诗', 'HOCC'] },
  { slug: 'ronald-cheng', group: 'male', name: '鄭中基', en: 'Ronald Cheng', debut: '1996', channelId: 'UCDwUaazcemLB7FLqGRESgFA', wiki: '鄭中基', aliases: ['郑中基'] },
  { slug: '1976', group: 'group', name: '1976', en: '', debut: '1996', channelId: 'UCBsLLQYAJCU5OPZ-Ea-K8zg', wiki: '1976 (樂團)' },
  { slug: 'tolaku', group: 'group', name: '脫拉庫', en: 'TOLAKU', debut: '1996', channelId: 'UCo0VFkSHgNgAkb-Rovup2Mw', extraChannelIds: ['UCx4VJ5sWTZs3kfNoztuRpyQ'], wiki: '脫拉庫' },
  { slug: 'shunza', group: 'female', name: '順子', en: 'Shunza', debut: '1996-11', channelId: 'UC-Cgo2VEj08oCVpbA2ME_IQ', wiki: '順子' },
  { slug: 'a-mei', group: 'female', name: '張惠妹', en: 'A-Mei', debut: '1996-12', channelId: 'UC5M7vIbPTCOMVF3lTtbeO6g', wiki: '張惠妹', aliases: ['Chang Hui Mei', 'aMEI', '阿密特', 'AMIT'] },
  { slug: 'tanya-chua', group: 'female', name: '蔡健雅', en: 'Tanya Chua', debut: '1997', channelId: 'UCKbk-Nog0Sac_NHWntf3RHQ', wiki: '蔡健雅' },
  { slug: 'panda-hsiung', group: 'male', name: '熊天平', en: 'Panda Hsiung', debut: '1997', channelId: 'UC7_HyHd-8qMYqUQ3r5TJA7w', wiki: '熊天平' },
  { slug: 'luantan-ascent', group: 'male', name: '乱彈阿翔', en: 'Ascent Chen', debut: '1997', channelId: 'UCMjgvKNBlQdvdf6n3IuRyEA', wiki: '乱彈阿翔', aliases: ['亂彈阿翔', '陳泰翔'] },
  { slug: 'kinmen-wang-lee-ping-hui', group: 'group', lang: 'tw', name: '金門王與李炳輝', en: '', debut: '1997', channelId: 'UCAP1eAINzi6zFj2dK7lU-Qg', wiki: '金門王', aliases: ['金門王', '李炳輝', '金門王、李炳輝'] },
  { slug: 'chairman', group: 'group', lang: 'tw', name: '董事長樂團', en: 'The Chairman', debut: '1997', channelId: 'UCOpOYi49F73aDTUgCZ63tRA', wiki: '董事長樂團', aliases: ['董事長', 'The Chairman Band'] },
  { slug: 'a-mei-mei', group: 'group', name: '阿妹妹', en: '', debut: '1997', channelId: 'UCAGBcDFs2GWkky4_ACXyjeg', wiki: null, members: ['張惠春', '陳秋琳'] },
  { slug: 'radiomars', group: 'group', name: '火星電台', en: 'RadioMars', debut: '1997', channelId: 'UCbiZhhDs87jHJZ0f8KE-QYQ', extraChannelIds: ['UCEv7tg_W__8MGL-TxMA3xTQ'], wiki: '火星電台', aliases: ['火星电台', '火星電臺'] },
  { slug: 'faith-yang', group: 'female', name: '楊乃文', en: 'Faith Yang', debut: '1997-07', channelId: 'UCvgxezGnDGWaQf8RLO46ljQ', aliases: ['Naiwen Yang'], wiki: '楊乃文' },
  { slug: 'power-station', group: 'group', name: '動力火車', en: 'Power Station', debut: '1997-10', channelId: 'UCl0TTFWfUV-JKfTbcFr5glQ', wiki: '動力火車', members: ['尤秋興', '顏志琳'] },
  { slug: 'shan-feng', group: 'group', name: '山風點夥', en: '', debut: '1997-10', channelId: 'UCmYBtZvqO1sUDekSDVgXlTg', wiki: null, aliases: ['山風點伙', '山風點火'] },
  { slug: 'david-tao', group: 'male', name: '陶喆', en: 'David Tao', debut: '1997-12', channelId: 'UCUfR8ZO3dAsLC5yQx1E4E9Q', wiki: '陶喆' },
  { slug: 'jin-xiu-duo', group: 'group', name: '錦繡二重唱', en: 'Jin Xiu Duo', debut: '1998', channelId: 'UCHPbRjEA5dCxUNYjy_98LUA', wiki: '錦繡二重唱', members: ['黃錦雯', '于子育'] },
  { slug: 'mc-hotdog', group: 'male', name: 'MC HotDog', en: '熱狗', debut: '1998', channelId: 'UCW3Q3F5SByAWsYtRRFIMuNA', wiki: 'MC HotDog', aliases: ['熱狗', '姚中仁'] },
  { slug: 'won-fu', group: 'group', name: '旺福', en: 'Won Fu', debut: '1998', channelId: 'UCepiuZrYlyLdN4vIBf7R5QQ', wiki: '旺福', members: ['小民', '瑪靡', '推機', '肚皮'] },
  { slug: 'chung-chien', group: 'group', name: '中堅份子', en: '', debut: '1998', channelId: 'UC31VXxZKNUfljAGwHi2rtQA', wiki: null },
  { slug: 'yuki-hsu', group: 'female', name: '徐懷鈺', en: 'Yuki Hsu', debut: '1998-01', channelId: 'UC2sIWB892N9NMFavWl53Zwg', wiki: '徐懷鈺' },
  { slug: 'cheer-chen', group: 'female', name: '陳綺貞', en: 'Cheer Chen', debut: '1998-07', channelId: 'UC3Sf91aR21dEBHWwOxzXCRw', wiki: '陳綺貞' },
  { slug: 'paudull', group: 'male', name: '陳建年', en: 'Paudull', debut: '1999', channelId: 'UC4uQtyIFtu6UmBeEhJ-ImLw', wiki: '陳建年 (歌手)' },
  { slug: 'showlen-maya', group: 'female', lang: 'tw', name: '秀蘭瑪雅', en: 'Showlen Maya', debut: '1999', channelId: 'UCL8aS0k47uZMRMbQVgUwYgA', extraChannelIds: ['UC2ZgukokgkcfBL6ZdzGTamg'], wiki: '秀蘭瑪雅' },
  { slug: 'samingad', group: 'female', name: '紀曉君', en: 'Samingad', debut: '1999', channelId: 'UCTOc6d2Wwd2y8tMk__r0i4Q', wiki: '紀曉君' },
  { slug: 'bowie-tsang', group: 'female', name: '曾寶儀', en: 'Bowie Tsang', debut: '1999', channelId: 'UCoBFo2EeIzEQnwVumKny7Yw', extraChannelIds: ['UCkMdOv3rgmpsVk6RBui0XBA'], wiki: '曾寶儀', aliases: ['曾宝仪'] },
  { slug: 'china-dolls', group: 'group', name: '中國娃娃', en: 'China Dolls', debut: '1999', channelId: 'UCUPBnJc9Pl9LcoTydXAJ1SQ', wiki: '中國娃娃 (組合)', members: ['陳冠樺', '李小燕', '劉佩君'] },
  { slug: 'tizzy-bac', group: 'group', name: 'Tizzy Bac', en: '', debut: '1999', channelId: 'UC3od9rPepMwiZry10oBObEA', wiki: 'Tizzy Bac', members: ['陳惠婷', '許哲毓', '林前源'] },
  { slug: 'band-100', group: 'group', name: '100%樂團', en: '100%', debut: '1999', channelId: 'UCGRoPIAxqyJYEcbYOVzC8TA', wiki: null, aliases: ['范曉萱&100%', '100%'] },
  { slug: 'angela-hou', group: 'female', name: '侯湘婷', en: 'Angela Hou', debut: '1999-01-01', channelId: 'UCBDKy7bVvfFvewBv4ZMjOKg', wiki: '侯湘婷' },
  { slug: 'sam-lee', group: 'male', name: '李聖傑', en: 'Sam Lee', debut: '1999-03', channelId: 'UCp6Mowp_ZCQojg25ICvOAAQ', wiki: '李聖傑' },
  { slug: 'ricky-hsiao', group: 'male', name: '蕭煌奇', en: 'Ricky Hsiao', debut: '1999-03', channelId: 'UCQw7Oil9u3xnFTm3SOI4eeg', wiki: '蕭煌奇' },
  { slug: 'maggie-chiang', group: 'female', name: '江美琪', en: 'Maggie Chiang', debut: '1999-06', channelId: 'UC-Rq0RvCNBwFSW6GThPSNCg', wiki: '江美琪' },
  { slug: 'mayday', group: 'group', name: '五月天', en: 'Mayday', debut: '1999-07', channelId: 'UCQyweuVOAh3NHGKDDadRSbg', wiki: '五月天', members: ['五月天阿信', '阿信', '瑪莎', '石頭', '怪獸', '冠佑'] },
  { slug: 'where-chou', group: 'female', name: '周蕙', en: 'Where Chou', debut: '1999-09', channelId: 'UC6Sn9AZ-8WPIwYlFdWlJtMQ', wiki: '周蕙' },
  { slug: 'jolin-tsai', group: 'female', name: '蔡依林', en: 'Jolin Tsai', debut: '1999-09-10', channelId: 'UC9dLsF7Ss7Wg0kR6TiIWiXg', wiki: '蔡依林' },
  { slug: 'fish-leong', group: 'female', name: '梁靜茹', en: 'Fish Leong', debut: '1999-09-17', channelId: 'UC8viexI7VBM6p632pCfTWRg', wiki: '梁靜茹' },
  { slug: 'elva-hsiao', group: 'female', name: '蕭亞軒', en: 'Elva Hsiao', debut: '1999-11', channelId: 'UCChWNfpWW8dUMmkgSWgOHKw', wiki: '蕭亞軒' },
  { slug: 'penny-tai', group: 'female', name: '戴佩妮', en: 'Penny Tai', debut: '2000', channelId: 'UCwdCmULcaKruVB5XMxT3gLg', wiki: '戴佩妮', groups: ['佛跳牆'] },
  { slug: 'fire-ex', group: 'group', lang: 'tw', name: '滅火器', en: 'Fire EX.', debut: '2000', channelId: 'UCcny0_3Z2DtcCEYayEcgtPg', aliases: ['滅火器樂團'], wiki: '滅火器樂團' },
  { slug: 'stanley-huang', group: 'male', name: '黃立行', en: 'Stanley Huang', debut: '2000', channelId: 'UC2Tl3yGEREKC0A9luaGuNDg', wiki: '黃立行', groups: ['L.A. Boyz'] },
  { slug: 'siri-lee', group: 'female', lang: 'tw', name: '李竺芯', en: 'Siri Lee', debut: '2000', channelId: 'UCEb_2hVk1bNs2nn-4F846uw', wiki: '李竺芯' },
  { slug: 'huang-fei', group: 'female', lang: 'tw', name: '黃妃', en: 'Huang Fei', debut: '2000', channelId: 'UCNW2L2mP4BPrmURZv4VZz_g', wiki: '黃妃' },
  { slug: 'penny-peng', group: 'female', name: '彭靖惠', en: 'Penny Peng', debut: '2000', channelId: 'UCt_FYdy4eitNnI-LdZx1f3g', wiki: '彭靖惠' },
  { slug: 'freya-lim', group: 'female', name: '林凡', en: 'Freya Lim', debut: '2000', channelId: 'UCstYHBZDAALuCsd1K6Vg44g', wiki: '林凡', aliases: ['Freya', 'Marco'] },
  { slug: 'huang-chia-chien', group: 'female', name: '黃嘉千', en: 'Huang Chia-chien', debut: '2000', channelId: 'UC7iuJZ8HycV7sO6M7_hXMyg', wiki: '黃嘉千' },
  { slug: '4-in-love', group: 'group', name: '4 in Love', en: '', debut: '2000', channelId: 'UCrb33aR12szWiFe1IpOZTow', wiki: null, members: ['冷嘉琳', '黃小柔', '楊丞琳', '張棋惠'] },
  { slug: 'kenji-wu', group: 'male', name: '吳克群', en: 'Kenji Wu', debut: '2000-11', channelId: 'UCkf2xPKEIy78LVKZ4GOFIVA', wiki: '吳克群' },
  { slug: 'jay-chou', group: 'male', name: '周杰倫', en: 'Jay Chou', debut: '2000-11', channelId: 'UCL2MDNdwEtV6aYUgNjFQGZA', wiki: '周杰倫' },
  { slug: 'bad', group: 'group', name: 'B.A.D', en: '', debut: '2000-12-17', channelId: 'UCVM3-sEjNWNT8_fT4wPd4wQ', extraChannelIds: ['UCzQo-uFPml3jeb2vWVb8E2g'], wiki: 'B.A.D', aliases: ['B.A.D.'], members: ['白吉勝', '田恩沛', '黃柏文'], cjkOnly: true },
  { slug: 'victor-wong', group: 'male', name: '品冠', en: 'Victor Wong', debut: '2001', channelId: 'UCZwxvbsLquj9TE0GxLbAXlw', wiki: '品冠', groups: ['無印良品', '光良品冠'] },
  { slug: 'f4', group: 'group', name: 'F4', en: '', debut: '2001', channelId: 'UCsXMXn3usu1aBmRpoDARBgw', wiki: 'F4 (台灣男子團體)', members: ['言承旭', '周渝民', '朱孝天', '吳建豪', 'Jerry Yan', 'Vic Chou', 'Ken Chu', 'Vanness Wu'] },
  { slug: 'hsu-che-pei', group: 'female', name: '許哲珮', en: 'Hsu Che-pei', debut: '2001', channelId: 'UCqwsO0KH07EGJ3KVf3aFs9g', wiki: '許哲珮', aliases: ['许哲珮'] },
  { slug: 'gary-chaw', group: 'male', name: '曹格', en: 'Gary Chaw', debut: '2001', channelId: 'UCUvbtTS_ngEj8QRuzjCiFfQ', wiki: '曹格', aliases: ['曹佰豪'] },
  { slug: 'z-chen', group: 'male', name: '張智成', en: 'Z-Chen', debut: '2001', channelId: 'UC8DDf1kx7DpK3sUb2xaZFZg', wiki: '張智成' },
  { slug: 'michael-wong', group: 'male', name: '光良', en: 'Michael Wong', debut: '2001-05-10', channelId: 'UCSuMl2pt6TsRXo2p0eGmC5g', wiki: '光良', groups: ['無印良品', '光良品冠'] },
  { slug: 'van-fan', group: 'male', name: '范逸臣', en: 'Van Fan', debut: '2001-07-27', channelId: 'UCqoMe2tW6uTwd0gqcZ9aVig', extraChannelIds: ['UCqLU1o11TEbTrLUJU1-dXvg'], wiki: '范逸臣' },
  { slug: 'she', group: 'group', name: 'S.H.E', en: '', debut: '2001-09', channelId: 'UCGH6l-Hozjs8vSW83e4u-Gw', wiki: 'S.H.E', members: ['任家萱', 'Selina', '田馥甄', 'Hebe', '陳嘉樺', 'Ella'] },
  { slug: 'angela-chang', group: 'female', name: '張韶涵', en: 'Angela Chang', debut: '2002', channelId: 'UCKeK5Xj-iCfLOZvMDm3aIkw', wiki: '張韶涵' },
  { slug: 'will-pan', group: 'male', name: '潘瑋柏', en: 'Will Pan', debut: '2002', channelId: 'UCLTkBdw-je3E7o47_C2hP3g', wiki: '潘瑋柏' },
  { slug: 'comic-boyz', group: 'group', name: '可米小子', en: 'Comic Boyz', debut: '2002', channelId: 'UCQHID2V6CiimCjLJYB9dh6g', wiki: '可米小子' },
  { slug: 'suming', group: 'male', name: '舒米恩', en: 'Suming', debut: '2002', channelId: 'UCHUd0hsJrT24c5T56WVaIcQ', extraChannelIds: ['UCQvVS0mTp5_Op0h1nFrQHtg', 'UCV2EC0bwt4rKEKic2XLGAEg'], wiki: '舒米恩', aliases: ['舒米恩·魯碧', 'Suming'] },
  { slug: 'danny-shao', group: 'male', lang: 'tw', name: '邵大倫', en: 'Danny Shao', debut: '2002', channelId: 'UCP6C2WYWCS3NfLzgdHjSGCw', wiki: '邵大倫' },
  { slug: 'a-do', group: 'male', name: '阿杜', en: 'A-do', debut: '2002', channelId: 'UCVaShxqKFyWkLBh_UH_SbaQ', wiki: '阿杜 (新加坡歌手)', aliases: ['杜成義'] },
  { slug: '5566', group: 'group', name: '5566', en: '', debut: '2002-01', channelId: 'UCNZAgq42kWS1YIdo43WJEwA', wiki: '5566', members: ['孫協志', '王仁甫', '許孟哲', '彭康育', '王少偉'] },
  { slug: 'evonne-hsu', group: 'female', name: '許慧欣', en: 'eVonne Hsu', debut: '2002-01-03', channelId: 'UC_XKGYLTdki0CzrSDpZ56SQ', wiki: '許慧欣', aliases: ['许慧欣'] },
  { slug: 'princess-ai', group: 'female', name: '戴愛玲', en: 'Princess Ai', debut: '2002-02-26', channelId: 'UChrZ-zEgQcYPnWq78uVJmhA', wiki: '戴愛玲', aliases: ['戴爱玲'] },
  { slug: 'dwagie', group: 'male', name: '大支', en: 'Dwagie', debut: '2002-07', channelId: 'UCzg9q6x9PNmp01UTZ8x3cRA', wiki: '大支' },
  { slug: 'energy', group: 'group', name: 'Energy', en: '', debut: '2002-07-12', channelId: 'UCU6hPT3E6ttqeSeOFnI65mw', wiki: 'Energy (台灣團體)', members: ['葉乃文', '郭葦昀', '張書偉', '謝坤達', '蕭景鴻', '唐振剛', '坤達', '書偉', '阿弟', '牛奶', 'Toro'] },
  { slug: 'hsieh-ming-yu', group: 'male', lang: 'tw', name: '謝銘祐', en: 'Hsieh Ming-yu', debut: '2002-12-17', channelId: 'UCTwfl0D7mGZ7oov4VM_3q4g', wiki: '謝銘祐', groups: ['麵包車'] },
  { slug: 'xiao-yu', group: 'male', name: '小宇', en: 'Xiao Yu', debut: '2003', channelId: 'UCor9onY76Nu9e4abGERRciQ', wiki: '小宇', aliases: ['宋念宇'] },
  { slug: 'cyndi-wang', group: 'female', name: '王心凌', en: 'Cyndi Wang', debut: '2003', channelId: 'UC-GYedjoXTj4tj8IOMZbp9g', wiki: '王心凌' },
  { slug: 'nicky-lee', group: 'male', name: '李玖哲', en: 'Nicky Lee', debut: '2003', channelId: 'UCR4CBIDq5hKp6hsCOLXasDA', wiki: '李玖哲' },
  { slug: 'machi', group: 'group', name: 'MACHI', en: '麻吉', debut: '2003', channelId: 'UCuBJZVnCZEYpyw4oGCNHmeQ', wiki: 'Machi (樂團)', aliases: ['麻吉', 'Machi', '黃立成 & 麻吉'] },
  { slug: 'natural-q', group: 'group', name: '自然捲', en: 'Natural Q', debut: '2003', channelId: 'UCy7dE7d4RqI84NwyN5l67nw', wiki: '自然捲 (樂團)', members: ['蔡坤奇', '魏如萱'] },
  { slug: 'jj-lin', group: 'male', name: '林俊傑', en: 'JJ Lin', debut: '2003-04', channelId: 'UCUJ3KuIIgvh8eVItvb-EdFQ', wiki: '林俊傑' },
  { slug: 'michelle-vickie', group: 'group', name: '蜜雪薇琪', en: 'Michelle & Vickie', debut: '2004', channelId: 'UCJfidJntxF85k2Zb22VGBLA', wiki: '蜜雪薇琪', aliases: ['Michelle Vickie'] },
  { slug: 'gogomeme', group: 'group', name: 'GoGoMeMe', en: '哥哥妹妹', debut: '2004', channelId: 'UCP5lSSTJPqIXbnVL2Uug8Ww', extraChannelIds: ['UC1z4pqR7vHybpK6Z4wa654A'], wiki: null, aliases: ['哥哥妹妹', 'GoGo 和 Meme', 'GoGo', 'Meme'], releases: ['MPREb_PKK6il0hGjD'] },
  { slug: 'nan-quan-mama', group: 'group', name: '南拳媽媽', en: 'Nan Quan Mama', debut: '2004', channelId: 'UCVem-YjIgnJPXZtBknopxog', wiki: '南拳媽媽', members: ['詹宇豪', '梁心頤', '張傑', '宋健彰'] },
  { slug: 'fir', group: 'group', name: 'F.I.R.', en: '飛兒樂團', debut: '2004-04-23', channelId: 'UCULDopO9sNa9kBs5QnFgmEQ', wiki: 'F.I.R.飛兒樂團', aliases: ['F.I.R', 'FIR', '飛兒樂團', '飞儿乐团'], members: ['詹雯婷', 'Faye', '陳建寧', '黃漢青', '阿沁'] },
  { slug: 'sodagreen', group: 'group', name: '蘇打綠', en: 'sodagreen', debut: '2004-05', channelId: 'UC_hqZWcuNgQnRTulFy6BN7w', extraChannelIds: ['UCUK1GVEFFX9Xv4mJjz8m55g'], wiki: '蘇打綠', aliases: ['魚丁糸', 'Oaeen'], members: ['吳青峰', '謝馨儀', '史俊威', '龔鈺祺', '劉家凱', '何景揚'] },
  { slug: 'ric-jan', group: 'male', lang: 'tw', name: '荒山亮', en: 'Ric Jan', debut: '2005', channelId: 'UCImdJ9Rjmn-xW4cjME94GNg', wiki: '荒山亮' },
  { slug: 'khalil-fong', group: 'male', name: '方大同', en: 'Khalil Fong', debut: '2005', channelId: 'UC_PRHIP9cby-5TBzhl4Oytg', wiki: '方大同' },
  { slug: '183-club', group: 'group', name: '183 Club', en: '', debut: '2005', channelId: 'UCRwfu77EOx73l4lp5cLNbMw', wiki: '183club' },
  { slug: 'yisa-yu', group: 'female', name: '郁可唯', en: 'Yisa Yu', debut: '2005', channelId: 'UCnXm2v7mhygE66HX9x3ituA', wiki: '郁可唯' },
  { slug: 'kimbo', group: 'male', name: '胡德夫', en: 'Kimbo Hu', debut: '2005-04', channelId: 'UCK860HsPUhFnfy3CiedIq5w', wiki: '胡德夫' },
  { slug: 'rainie-yang', group: 'female', name: '楊丞琳', en: 'Rainie Yang', debut: '2005-09', channelId: 'UC0WDze0vAMrLxULTWMlSuRA', wiki: '楊丞琳', groups: ['4 In Love'] },
  { slug: 'fahrenheit', group: 'group', name: '飛輪海', en: 'Fahrenheit', debut: '2005-12-28', channelId: 'UCdN_zNvwux-Fh1gjlbsWZGQ', wiki: '飛輪海', members: ['吳尊', '辰亦儒', '汪東城', '炎亞綸', 'Wu Chun', 'Jiro Wang', 'Aaron Yan', 'Calvin Chen'] },
  { slug: 'a-lin', group: 'female', name: 'A-Lin', en: '黃麗玲', debut: '2006', channelId: 'UCh8MAQTB0y4JMTROjINKenA', wiki: 'A-Lin', aliases: ['黃麗玲'] },
  { slug: 'hey-girl', group: 'group', name: '黑Girl', en: 'Hey Girl', debut: '2006', channelId: 'UCoQVyEia0rK1Baf4rDZRNVA', wiki: '黑Girl', aliases: ['黑girl', '九妞妞'] },
  { slug: 'lollipop', group: 'group', name: '棒棒堂', en: 'Lollipop', debut: '2006-12-02', channelId: 'UCb5pkLhsbQfTZvD2-Zlzcsg', wiki: '棒棒堂', aliases: ['Lollipop F', 'Lollipop@F', 'Lollipop-F', 'Lollipop 棒棒堂'], members: ['敖犬', '王子', '小煜', '小杰', '威廉', '阿緯', '邱勝翊', '莊濠全', '楊奇煜', '廖允杰', '廖亦崟', '劉峻緯'] },
  { slug: 'yoga-lin', group: 'male', name: '林宥嘉', en: 'Yoga Lin', debut: '2007', channelId: 'UC8VIeph9z_a5jHiHxqFjLPg', wiki: '林宥嘉' },
  { slug: 'aska-yang', group: 'male', name: '楊宗緯', en: 'Aska Yang', debut: '2007', channelId: 'UC3foh7LHNHBPpcA53e3pikA', wiki: '楊宗緯' },
  { slug: '831', group: 'group', name: '八三夭', en: '831', debut: '2007', channelId: 'UCVBiSWmgpzvCFs6ULFTh50A', extraChannelIds: ['UCSdOayBNVsRd1tBxA8LiLLQ'], wiki: '八三夭' },
  { slug: 'crowd-lu', group: 'male', name: '盧廣仲', en: 'Crowd Lu', debut: '2007-04-13', channelId: 'UCTPByZ54kHfs6pwoGNAcCzQ', wiki: '盧廣仲' },
  { slug: 'claire-kuo', group: 'female', name: '郭靜', en: 'Claire Kuo', debut: '2007-06-29', channelId: 'UCYYhiWcofKhHQuqYD7BUoRw', wiki: '郭靜', aliases: ['郭静'] },
  { slug: 'della-ding', group: 'female', name: '丁噹', en: 'Della Ding', debut: '2007-07-06', channelId: 'UCATB6fk4_-ySg0CzlQFHLaQ', extraChannelIds: ['UClU_SGeH66YsSbB8Y5cQ1FA'], wiki: '丁噹', aliases: ['丁当', 'Della'] },
  { slug: 'ella-chen', group: 'female', name: '陳嘉樺', en: 'Ella', debut: '2007-08-24', channelId: 'UCKNyuOBLJRpxgh-AofB89-g', wiki: '陳嘉樺', aliases: ['陳嘉樺', 'Ella Chen'], groups: ['S.H.E'] },
  { slug: 'waa-wei', group: 'female', name: '魏如萱', en: 'Waa Wei', debut: '2007-11', channelId: 'UCYul_G85M2ySouSZlqX_ipg', wiki: '魏如萱', groups: ['自然捲'] },
  { slug: 'da-mouth', group: 'group', name: '大嘴巴', en: 'Da Mouth', debut: '2007-11-16', channelId: 'UC2RY9yh7CmrJp2myNK8SYVA', wiki: '大嘴巴', members: ['愛紗', '懷秋', '薛仕凌', 'MC40', '坂本宗華', '宗華'] },
  { slug: 'jam-hsiao', group: 'male', name: '蕭敬騰', en: 'Jam Hsiao', debut: '2008', channelId: 'UCvjGf4upqUNaqi524A5AHIw', wiki: '蕭敬騰' },
  { slug: 'joanna-wang', group: 'female', name: '王若琳', en: 'Joanna Wang', debut: '2008', channelId: 'UCyjLXrYlY-xzieUwYJXIFFg', wiki: '王若琳' },
  { slug: 'ma-nien-hsien', group: 'male', name: '馬念先', en: 'Ma Nien-hsien', debut: '2008', channelId: 'UCfuLDbI19x13i0pUn9iQqyA', wiki: '馬念先', aliases: ['馬拉桑'], groups: ['糯米糰'] },
  { slug: 'superband', group: 'group', name: '縱貫線', en: 'SuperBand', debut: '2008', channelId: 'UCVqh1aqyTQTPqp6MTXZIB6g', wiki: '縱貫線 (樂團)', members: ['羅大佑', '李宗盛', '周華健', '張震嶽'] },
  { slug: 'e-so', group: 'male', name: '瘦子E.SO', en: 'Eddie Chen', debut: '2008-07-04', channelId: 'UC6XU7kBQgXS7Fpa5ka_KUhg', wiki: '瘦子E.SO', aliases: ['瘦子', 'E.SO', '陳昱榕'] },
  { slug: 'gem', group: 'female', name: '鄧紫棋', en: 'G.E.M.', debut: '2008-07-10', channelId: 'UCBRh2Z_U1Lw9-YJ-XGZ8M2Q', wiki: '鄧紫棋', aliases: ['邓紫棋', 'GEM'] },
  { slug: 'soft-lipa', group: 'male', name: '蛋堡', en: 'Soft Lipa', debut: '2009', channelId: 'UCPMkOsBp-jRezKYBR_9XEaA', wiki: '蛋堡 (音樂人)', aliases: ['杜振熙', 'Soft Lipa'] },
  { slug: 'lala-hsu', group: 'female', name: '徐佳瑩', en: 'LaLa Hsu', debut: '2009', channelId: 'UC974iWoR_ZhWT6cNbZSaEdg', wiki: '徐佳瑩' },
  { slug: 'hanya-chang', group: 'female', lang: 'tw', name: '張涵雅', en: 'Hanya', debut: '2009', channelId: 'UCVtvZY2TcfcjQ8CNmnFGB3w', wiki: '張涵雅' },
  { slug: 'cosmos-people', group: 'group', name: '宇宙人', en: 'Cosmos People', debut: '2009', channelId: 'UCWSyWCpk81aAcHlkcADHPeg', wiki: '宇宙人 (台灣樂團)', members: ['林忠諭', '陳奎言', '方奎棠'] },
  { slug: 'sunset-rollercoaster', group: 'group', name: '落日飛車', en: 'Sunset Rollercoaster', debut: '2009', channelId: 'UCuuF4aW1yEQqlTwu8u5zLYw', wiki: '落日飛車' },
  { slug: 'william-wei', group: 'male', name: '韋禮安', en: 'William Wei', debut: '2009-03', channelId: 'UCRRM_02oKgCCZO359HnMUnQ', wiki: '韋禮安', aliases: ['韦礼安', 'WeiBird'] },
  { slug: '911', group: 'group', name: '玖壹壹', en: '', debut: '2009-09-11', channelId: 'UCo03c_Gybw36U7Nd3ZIBmHg', wiki: '玖壹壹', aliases: ['九壹壹'], members: ['春風', '洋蔥', '健志'] },
  { slug: 'magic-power', group: 'group', name: 'MP魔幻力量', en: 'Magic Power', debut: '2009-12-29', channelId: 'UCdF2zM4s1fAJb9mJ8eQNiaQ', wiki: 'MP魔幻力量', members: ['潘俊佳', '黃柏翔', '蕭秉治', '呂思緯', '賴世凱', '李柏誼'] },
  { slug: 'matzka', group: 'male', name: 'Matzka', en: '瑪斯卡', debut: '2010', channelId: 'UCGhCPrkRpczFtI8dbam9SPg', wiki: 'Matzka', aliases: ['MATZKA', '宋唯農'] },
  { slug: 'eve-ai', group: 'female', name: '艾怡良', en: 'Eve Ai', debut: '2010', channelId: 'UC_igPX3c9gOMQ41hSDV8tNg', wiki: '艾怡良' },
  { slug: 'nick-chou', group: 'male', name: '周湯豪', en: 'Nick Chou', debut: '2010', channelId: 'UCm0Nc9JRha2Gxq5AlBXWElQ', aliases: ['Nickthereal', 'NICKTHEREAL'], wiki: '周湯豪' },
  { slug: 'hung-pei-yu', group: 'female', name: '洪佩瑜', en: 'Hung Pei-yu', debut: '2010', channelId: 'UCiqp2-ITbRVmlct3XQRF0VQ', wiki: '洪佩瑜' },
  { slug: 'hush', group: 'male', name: 'HUSH', en: '陳品赫', debut: '2010', channelId: 'UCbWVjBuVDZaVf3kDlUBud8w', wiki: 'Hush (歌手)', aliases: ['hush!', '陳品赫'] },
  { slug: 'olivia-tsao', group: 'female', lang: 'tw', name: '曹雅雯', en: 'Olivia Tsao', debut: '2010', channelId: 'UC-hrtPHYJCQuviEsJtl7eOg', extraChannelIds: ['UCm1ytaApJP5ejf_bNxDz8Pg', 'UCAq4fIMWGKnKTRcUKK72SBw'], wiki: '曹雅雯' },
  { slug: 'hebe-tien', group: 'female', name: '田馥甄', en: 'Hebe Tien', debut: '2010-09', channelId: 'UCGkj4uoWx_1BA2tF9Q-9Y6w', wiki: '田馥甄', groups: ['S.H.E'] },
  { slug: 'enno-cheng', group: 'female', lang: 'tw', name: '鄭宜農', en: 'Enno Cheng', debut: '2011', channelId: 'UCBwvmIwEkwJnUM7UYxu32pw', wiki: '鄭宜農' },
  { slug: 'henry-hsu', group: 'male', lang: 'tw', name: '許富凱', en: 'Henry Hsu', debut: '2011', channelId: 'UCzWtWnUu-klp-esK22WZ09A', wiki: '許富凱' },
  { slug: 'buddha-jump', group: 'group', name: '佛跳牆', en: 'Buddha Jump', debut: '2011-08', channelId: 'UCDUFxGQYrCV0c-B0V13vgrw', wiki: '佛跳牆 (樂團)', members: ['戴佩妮', '黃宣銘', '陳君豪'] },
  { slug: 'joey-chiang', group: 'female', lang: 'tw', name: '江惠儀', en: 'Joey', debut: '2011-09-06', channelId: 'UCAvhiWda9p6tb3py9PBQQnA', wiki: '江惠儀' },
  { slug: 'miss-ko', group: 'female', name: '葛仲珊', en: 'Miss Ko', debut: '2012', channelId: 'UCg1fp_qvYdOe4rgua-A63kQ', wiki: '葛仲珊', aliases: ['Miss Ko'] },
  { slug: 'no-party-for-cao-dong', group: 'group', name: '草東沒有派對', en: 'No Party For Cao Dong', debut: '2012', channelId: 'UC-1kIjeEOX6NkWWKX3Y1W8Q', wiki: '草東沒有派對' },
  { slug: 'elephant-gym', group: 'group', name: '大象體操', en: 'Elephant Gym', debut: '2012-02', channelId: 'UCHdiJPav8suNipQrhdrJjWA', wiki: '大象體操' },
  { slug: 'mixer', group: 'group', name: '麋先生', en: 'Mixer', debut: '2012-10-17', channelId: 'UC8-28YYfF3CszynLHSn9Dig', wiki: '麋先生' },
  { slug: 'sangpuy', group: 'male', name: '桑布伊', en: 'Sangpuy', debut: '2012-11-06', channelId: 'UCOTQ1T0t7s3fWdCXmj3CBEA', wiki: '桑布伊', aliases: ['Sangpuy Katatepan Mavaliyw'] },
  { slug: 'jia-jia', group: 'female', name: '家家', en: 'JiaJia', debut: '2012-12', channelId: 'UCfQNuvDQMiZzqy3I-b7g6VA', wiki: '紀家盈', aliases: ['紀家盈'], groups: ['昊恩家家'] },
  { slug: 'ronghao-li', group: 'male', name: '李榮浩', en: 'Ronghao Li', debut: '2013', channelId: 'UCLZ9hbBmb_5mEclHVY5yOBg', wiki: '李榮浩' },
  { slug: 'li-ying-hung', group: 'male', name: '李英宏', en: 'DJ Didilong', debut: '2013', channelId: 'UCh3NuqiqEW2J57qJm5Er9Pg', extraChannelIds: ['UC8G3pwY5VOg60r6CsukBMDg'], wiki: '李英宏', aliases: ['李英宏 aka DJ Didilong', 'DJ Didilong'] },
  { slug: 'greg-han', group: 'male', name: '許光漢', en: 'Greg Han', debut: '2013', channelId: 'UC1y6D7uAGKH-3odTm00x-Sw', wiki: '許光漢', aliases: ['Greg Hsu'] },
  { slug: 'jacky-chen', group: 'male', lang: 'tw', name: '陳建瑋', en: 'Jacky Chen', debut: '2013-12', channelId: 'UCd5jew3OrvlJCU5G6CpiLBg', wiki: '陳建瑋' },
  { slug: 'eric-chou', group: 'male', name: '周興哲', en: 'Eric Chou', debut: '2014', channelId: 'UCawsPaLRTeYnWvthH8pepBw', wiki: '周興哲' },
  { slug: 'dee-hsu', group: 'female', name: '徐熙娣', en: '小S', debut: '2014', channelId: 'UCmoPrMwoUi3vVzy8QRWTACw', wiki: '徐熙娣', aliases: ['小S', 'elephant DEE', 'Dee Hsu'], groups: ['SOS', 'ASOS', 'S.O.S', 'SOS (大S+小S)'] },
  { slug: 'kumachan', group: 'male', name: '熊仔', en: 'Kumachan', debut: '2014', channelId: 'UCrxZ8selwnTadeJMwLqH8CQ', wiki: '熊仔', aliases: ['熊信寬'] },
  { slug: 'shi-shi', group: 'female', name: '孫盛希', en: 'Shi Shi', debut: '2014-06', channelId: 'UCY4wdFAd6x2tupBrOAVYMVA', wiki: '孫盛希', aliases: ['孙盛希', 'Shi Shi'] },
  { slug: 'j-sheon', group: 'male', name: 'J.Sheon', en: '莊珣', debut: '2015', channelId: 'UCi6MXUg7agTF7m0MgOjE9AA', wiki: 'J.Sheon', aliases: ['街巷', '莊珣'] },
  { slug: 'kowen-ko', group: 'male', name: '柯智棠', en: 'Kowen Ko', debut: '2015', channelId: 'UCoN-Zm473fCcBzNIxPwM2Aw', wiki: '柯智棠' },
  { slug: '9m88', group: 'female', name: '9m88', en: '', debut: '2016', channelId: 'UCpZvDKDJtQUXm1o6LKT2xhA', wiki: '9m88' },
  { slug: 'amazing-show', group: 'group', lang: 'tw', name: '美秀集團', en: 'Amazing Show', debut: '2016', channelId: 'UC9fwTdQyoeDFhOhNN3CQDlg', wiki: '美秀集團' },
  { slug: 'leo-wang', group: 'male', name: 'Leo王', en: 'Leo Wang', debut: '2016', channelId: 'UCUqJ2PHIPNsgEeoQxf9NqQw', wiki: 'Leo王', aliases: ['Leo 王', '王之佑'], groups: ['夜貓組', '巨大的轟鳴'] },
  { slug: 'cheng-hsing', group: 'male', name: '鄭興', en: 'Xing Zheng', debut: '2016', channelId: 'UC0PF49LFq1WNPtIQgjCxtog', wiki: '鄭興 (歌手)' },
  { slug: 'sweet-john', group: 'group', name: '甜約翰', en: 'Sweet John', debut: '2016', channelId: 'UC7xn0mpbaticwKL02M63oNA', wiki: '甜約翰' },
  { slug: 'eggplantegg', group: 'group', lang: 'tw', name: '茄子蛋', en: 'EggPlantEgg', debut: '2017', channelId: 'UChQoPspEw6hGSwQQDOLpeqg', wiki: '茄子蛋', members: ['黃奇斌', '蔡鎧任', '謝耀德'] },
  { slug: 'accusefive', group: 'group', name: '告五人', en: 'Accusefive', debut: '2017', channelId: 'UC2lbjBep5vvd-Spo0oGn97g', wiki: '告五人', members: ['潘雲安', '犬青'] },
  { slug: 'ozi', group: 'male', name: 'ØZI', en: '陳奕凡', debut: '2017', channelId: 'UCIWAZb-3mUohrtuyhbW4t8g', wiki: 'ØZI', aliases: ['OZI', '陳奕凡'] },
  { slug: 'mango-jump', group: 'group', name: '芒果醬', en: 'Mango Jump', debut: '2017-04-06', channelId: 'UCz2OKKY3n0LgVPYsI2mr9HA', wiki: '芒果醬', members: ['郭佐治', '蔡有倫', '李皝達', '黃聖智'] },
  { slug: 'faye', group: 'female', name: 'Faye 飛', en: '詹雯婷', debut: '2017-06', channelId: 'UCjA1vzKnKAOztVU_XUYAWVg', wiki: '詹雯婷', aliases: ['詹雯婷', 'Faye', 'Faye詹雯婷'], groups: ['F.I.R.', 'F.I.R', '飛兒樂團'] },
  { slug: 'trout-fresh', group: 'male', name: '呂士軒', en: 'Trout Fresh', debut: '2017-12', channelId: 'UCTy299dJVLtJ8G6r9fJ6PMw', wiki: '呂士軒' },
  { slug: 'qingfeng-wu', group: 'male', name: '吳青峰', en: 'Qingfeng Wu', debut: '2018', channelId: 'UCcMXwG8ppb2YO4ibv6C18rg', wiki: '吳青峰', groups: ['蘇打綠', 'sodagreen', '魚丁糸'] },
  { slug: 'yellow-huang', group: 'male', name: '黃宣', en: 'YELLOW', debut: '2018', channelId: 'UC8LSDyzBofOA3AbXNFxCkEA', wiki: '黃宣', aliases: ['YELLOW黃宣', 'YELLOW'] },
  { slug: 'bestards', group: 'group', name: '理想混蛋', en: 'Bestards', debut: '2018', channelId: 'UC5AUnQFb4CUE2c4rua_zJKw', wiki: '理想混蛋' },
  { slug: 'jude-chiu', group: 'male', name: '裘德', en: 'Jude Chiu', debut: '2018-02-16', channelId: 'UCqPoNMjQP251NIeX7t1rZNg', extraChannelIds: ['UCX10cx2Wl7g-FkHZ1Vzah8Q'], wiki: '裘德', aliases: ['趙熙南', '赵熙南'] },
  { slug: 'wolfs', group: 'group', name: '五堅情', en: 'W0LF(S)', debut: '2019-11-19', channelId: 'UCcVii92kfoedo4LX9Gw97-w', wiki: '五堅情', aliases: ['四堅情', 'WOLF(S)'], members: ['陳零九', '邱鋒澤', '黃偉晉', '賴晏駒', '婁峻碩'] },
  { slug: 'dinosaurs-skin', group: 'group', name: '恐龍的皮', en: "The Dinosaur's Skin", debut: '2021', channelId: 'UCUauzzLF1_CpV8tyXdXJ3Sw', wiki: '恐龍的皮' },
  { slug: 'for-what', group: 'group', name: '浮花樂隊', en: 'For What', debut: '2022', channelId: 'UCry9S-7wth479tbrtiP_l9A', wiki: null },
]

// 首頁分頁：key 是網址（華語沿用原本的 female／male／group）
export const GROUPS = [
  { key: 'male', label: '華語男歌手', title: '天王', unit: '位' },
  { key: 'female', label: '華語女歌手', title: '天后', unit: '位' },
  { key: 'group', label: '華語團體', title: '團體', unit: '組' },
  { key: 'tw-male', label: '台語男歌手', title: '台語天王', unit: '位' },
  { key: 'tw-female', label: '台語女歌手', title: '台語天后', unit: '位' },
  { key: 'tw-group', label: '台語團體', title: '台語團體', unit: '組' },
]

/** 藝人所屬分頁：tw-female、female… */
export const categoryOf = (artist) => (artist.lang === 'tw' ? `tw-${artist.group}` : artist.group)

export const artistsIn = (category) => ARTISTS.filter((a) => categoryOf(a) === category)

export const findArtist = (slug) => ARTISTS.find((a) => a.slug === slug)
