// 各歌手在 YouTube Music 的官方藝人頻道與 Wikipedia 條目；slug 用於網址與資料檔名。
// 前端與 Node 抓取腳本共用這份清單，依出道日期（Wikipedia 資訊框的出道日期／出道作發行）排列。
export const ARTISTS = [
  { slug: 'ouyang-fei-fei', name: '歐陽菲菲', en: 'Ouyang Fei Fei', debut: '1966', channelId: 'UC5nvsmdF62lN570NZdxq84g', wiki: '歐陽菲菲' },
  { slug: 'teresa-teng', name: '鄧麗君', en: 'Teresa Teng', debut: '1967', channelId: 'UCI2cy2lwlzMksxEu63E8Zag', wiki: '鄧麗君' },
  { slug: 'feng-fei-fei', name: '鳳飛飛', en: 'Feng Fei Fei', debut: '1968', channelId: 'UCylxmFpXSfOsnuaOn5NCc1g', wiki: '鳳飛飛' },
  { slug: 'sarah-chen', name: '陳淑樺', en: 'Sarah Chen', debut: '1973', channelId: 'UCCmIJng9-OXs9Ax5P4-m8UA', wiki: '陳淑樺' },
  { slug: 'tracy-huang', name: '黃鶯鶯', en: 'Tracy Huang', debut: '1974', channelId: 'UCmQWBgcJyjLBdoF428F6y1A', wiki: '黃鶯鶯' },
  { slug: 'chyi-yu', name: '齊豫', en: 'Chyi Yu', debut: '1978', channelId: 'UCN82-y6I2oH9Tw8LaPw2sYg', wiki: '齊豫' },
  { slug: 'tsai-chin', name: '蔡琴', en: 'Tsai Chin', debut: '1979', channelId: 'UCiqpapiuXXw7y0BdBXL-hzA', wiki: '蔡琴' },
  { slug: 'yvonne-cheng', name: '鄭怡', en: 'Yvonne Cheng', debut: '1979', channelId: 'UCuvGX4pEScIUjZ4fuvFraaw', wiki: '鄭怡' },
  { slug: 'michelle-pan', name: '潘越雲', en: 'Michelle Pan', debut: '1979-10', channelId: 'UCCaauu_jc2rhNsx66SYjTKQ', wiki: '潘越雲' },
  { slug: 'jody-chiang', name: '江蕙', en: 'Jody Chiang', debut: '1981-04', channelId: 'UCJHd5tIDLb6YuNg3L_Ad15A', wiki: '江蕙' },
  { slug: 'anita-mui', name: '梅艷芳', en: 'Anita Mui', debut: '1982', channelId: 'UCllyCYlWEeBeZ4v3kNqz0AA', wiki: '梅艷芳' },
  { slug: 'julie-sue', name: '蘇芮', en: 'Julie Sue', debut: '1983', channelId: 'UC7GaEq4YeIndQAmWZGCp1jA', wiki: '蘇芮' },
  { slug: 'stella-chang', name: '張清芳', en: 'Stella Chang', debut: '1984', channelId: 'UCgqKZd77uZDWKtZYViztZng', wiki: '張清芳' },
  { slug: 'sandy-lam', name: '林憶蓮', en: 'Sandy Lam', debut: '1985', channelId: 'UChwNyOQOnJ6n1H5EDnkpXhw', wiki: '林憶蓮' },
  { slug: 'winnie-hsin', name: '辛曉琪', en: 'Winnie Hsin', debut: '1986', channelId: 'UCmC8dCKfO3ZZtxYNvkadmxA', wiki: '辛曉琪' },
  { slug: 'huang-yee-ling', name: '黃乙玲', en: 'Huang Yee-ling', debut: '1987', channelId: 'UCvAECH-laxIYOFxLmeRjcjA', wiki: '黃乙玲' },
  { slug: 'cyndi-chao', name: '趙詠華', en: 'Cyndi Chao', debut: '1988', channelId: 'UCSCwNNMlx6buDMAvK4K6PGA', wiki: '趙詠華' },
  { slug: 'na-ying', name: '那英', en: 'Na Ying', debut: '1988', channelId: 'UC7tVAVl0FfQ4ylidGciMJZQ', wiki: '那英' },
  { slug: 'faye-wong', name: '王菲', en: 'Faye Wong', debut: '1989', channelId: 'UCnAmvOfJxmcMd5q48BEIuPQ', wiki: '王菲' },
  { slug: 'wan-fang', name: '萬芳', en: 'Wan Fang', debut: '1990', channelId: 'UC7W9UR7f56ZcmN-fGg4Pvww', wiki: '萬芳' },
  { slug: 'tarcy-su', name: '蘇慧倫', en: 'Tarcy Su', debut: '1990-03', channelId: 'UCuzREF7riRhr2BWRqEBcjBA', wiki: '蘇慧倫' },
  { slug: 'tiger-huang', name: '黃小琥', en: 'Tiger Huang', debut: '1990-08', channelId: 'UCV6FKRsG3xal52heBj_XWkA', wiki: '黃小琥' },
  { slug: 'sammi-cheng', name: '鄭秀文', en: 'Sammi Cheng', debut: '1990', channelId: 'UCM8Xiz5yxDCdsP_o6ihVcaA', wiki: '鄭秀文' },
  { slug: 'karen-mok', name: '莫文蔚', en: 'Karen Mok', debut: '1993', channelId: 'UChrwddvlCf1df9skygWPA6g', wiki: '莫文蔚' },
  { slug: 'mavis-hee', name: '許美靜', en: 'Mavis Hee', debut: '1994', channelId: 'UCHl4oR3WDrHi49L2M6m33MA', wiki: '許美靜' },
  { slug: 'coco-lee', name: '李玟', en: 'CoCo Lee', debut: '1994-06', channelId: 'UCVzDS3qH_E2ooA7AimOrzHQ', wiki: '李玟' },
  { slug: 'valen-hsu', name: '許茹芸', en: 'Valen Hsu', debut: '1995-06', channelId: 'UCZgpCUQ69DOR8OUKAxD8exw', wiki: '許茹芸' },
  { slug: 'rene-liu', name: '劉若英', en: 'Rene Liu', debut: '1995', channelId: 'UCWY-I1axwr3X9YiouSwHf5Q', wiki: '劉若英' },
  { slug: 'mavis-fan', name: '范曉萱', en: 'Mavis Fan', debut: '1995', channelId: 'UCpCPwuMLFLFAWdHE3RWFjqg', wiki: '范曉萱' },
  { slug: 'julia-peng', name: '彭佳慧', en: 'Julia Peng', debut: '1996', channelId: 'UC1tBiwuyXgWNLWiUpx53TRA', wiki: '彭佳慧' },
  { slug: 'gigi-leung', name: '梁詠琪', en: 'Gigi Leung', debut: '1996', channelId: 'UC_yk6-0jRw__Ys5cakYotcg', wiki: '梁詠琪' },
  { slug: 'shunza', name: '順子', en: 'Shunza', debut: '1996-11', channelId: 'UC-Cgo2VEj08oCVpbA2ME_IQ', wiki: '順子' },
  { slug: 'a-mei', name: '張惠妹', en: 'A-Mei', debut: '1996-12', channelId: 'UC5M7vIbPTCOMVF3lTtbeO6g', wiki: '張惠妹' },
  { slug: 'tanya-chua', name: '蔡健雅', en: 'Tanya Chua', debut: '1997', channelId: 'UCKbk-Nog0Sac_NHWntf3RHQ', wiki: '蔡健雅' },
  { slug: 'faith-yang', name: '楊乃文', en: 'Faith Yang', debut: '1997-07', channelId: 'UCvgxezGnDGWaQf8RLO46ljQ', wiki: '楊乃文' },
  { slug: 'cheer-chen', name: '陳綺貞', en: 'Cheer Chen', debut: '1998-07', channelId: 'UC3Sf91aR21dEBHWwOxzXCRw', wiki: '陳綺貞' },
  { slug: 'jolin-tsai', name: '蔡依林', en: 'Jolin Tsai', debut: '1999-09-10', channelId: 'UC9dLsF7Ss7Wg0kR6TiIWiXg', wiki: '蔡依林' },
  { slug: 'fish-leong', name: '梁靜茹', en: 'Fish Leong', debut: '1999-09-17', channelId: 'UC8viexI7VBM6p632pCfTWRg', wiki: '梁靜茹' },
  { slug: 'elva-hsiao', name: '蕭亞軒', en: 'Elva Hsiao', debut: '1999-11', channelId: 'UCChWNfpWW8dUMmkgSWgOHKw', wiki: '蕭亞軒' },
  { slug: 'penny-tai', name: '戴佩妮', en: 'Penny Tai', debut: '2000', channelId: 'UCwdCmULcaKruVB5XMxT3gLg', wiki: '戴佩妮' },
  { slug: 'rainie-yang', name: '楊丞琳', en: 'Rainie Yang', debut: '2000', channelId: 'UC0WDze0vAMrLxULTWMlSuRA', wiki: '楊丞琳' },
  { slug: 'christine-fan', name: '范瑋琪', en: 'Christine Fan', debut: '2000-11', channelId: 'UC49ijorxlIXpZRAC6wEQYWQ', wiki: '范瑋琪' },
  { slug: 'hebe-tien', name: '田馥甄', en: 'Hebe Tien', debut: '2001-09', channelId: 'UCGkj4uoWx_1BA2tF9Q-9Y6w', wiki: '田馥甄' },
  { slug: 'angela-chang', name: '張韶涵', en: 'Angela Chang', debut: '2002', channelId: 'UCKeK5Xj-iCfLOZvMDm3aIkw', wiki: '張韶涵' },
  { slug: 'waa-wei', name: '魏如萱', en: 'Waa Wei', debut: '2003', channelId: 'UCYul_G85M2ySouSZlqX_ipg', wiki: '魏如萱' },
  { slug: 'cyndi-wang', name: '王心凌', en: 'Cyndi Wang', debut: '2003', channelId: 'UC-GYedjoXTj4tj8IOMZbp9g', wiki: '王心凌' },
  { slug: 'a-lin', name: 'A-Lin', en: '黃麗玲', debut: '2006', channelId: 'UCh8MAQTB0y4JMTROjINKenA', wiki: 'A-Lin' },
  { slug: 'lala-hsu', name: '徐佳瑩', en: 'LaLa Hsu', debut: '2009', channelId: 'UC974iWoR_ZhWT6cNbZSaEdg', wiki: '徐佳瑩' },
  { slug: 'eve-ai', name: '艾怡良', en: 'Eve Ai', debut: '2010', channelId: 'UC_igPX3c9gOMQ41hSDV8tNg', wiki: '艾怡良' },
  { slug: '9m88', name: '9m88', en: '', debut: '2016', channelId: 'UCpZvDKDJtQUXm1o6LKT2xhA', wiki: '9m88' },
]

export const findArtist = (slug) => ARTISTS.find((a) => a.slug === slug)
