// 各歌手在 YouTube Music 的官方藝人頻道與 Wikipedia 條目；slug 用於網址與資料檔名。
// 前端與 Node 抓取腳本共用這份清單，依出道日期（Wikipedia 資訊框的出道日期／出道作發行）排列。
// group：female 女歌手、male 男歌手、group 團體，首頁依此分頁。
// extraChannelIds：作品分散在其他頻道時一併抓取合併。
// aliases：曲目演出者欄可能出現的其他名字（舊藝名、外語名、團員），用來判斷是不是這位歌手唱的。
export const ARTISTS = [
  { slug: 'ouyang-fei-fei', group: 'female', name: '歐陽菲菲', en: 'Ouyang Fei Fei', debut: '1966', channelId: 'UC5nvsmdF62lN570NZdxq84g', wiki: '歐陽菲菲' },
  { slug: 'teresa-teng', group: 'female', name: '鄧麗君', en: 'Teresa Teng', debut: '1967', channelId: 'UCI2cy2lwlzMksxEu63E8Zag', wiki: '鄧麗君', aliases: ['テレサ・テン'] },
  { slug: 'feng-fei-fei', group: 'female', name: '鳳飛飛', en: 'Feng Fei Fei', debut: '1968', channelId: 'UCylxmFpXSfOsnuaOn5NCc1g', wiki: '鳳飛飛' },
  { slug: 'sarah-chen', group: 'female', name: '陳淑樺', en: 'Sarah Chen', debut: '1973', channelId: 'UCCmIJng9-OXs9Ax5P4-m8UA', wiki: '陳淑樺' },
  { slug: 'tracy-huang', group: 'female', name: '黃鶯鶯', en: 'Tracy Huang', debut: '1974', channelId: 'UCmQWBgcJyjLBdoF428F6y1A', wiki: '黃鶯鶯' },
  { slug: 'chyi-yu', group: 'female', name: '齊豫', en: 'Chyi Yu', debut: '1978', channelId: 'UCN82-y6I2oH9Tw8LaPw2sYg', wiki: '齊豫' },
  { slug: 'tsai-chin', group: 'female', name: '蔡琴', en: 'Tsai Chin', debut: '1979', channelId: 'UCiqpapiuXXw7y0BdBXL-hzA', wiki: '蔡琴', aliases: ['Cai Qin'] },
  { slug: 'yvonne-cheng', group: 'female', name: '鄭怡', en: 'Yvonne Cheng', debut: '1979', channelId: 'UCuvGX4pEScIUjZ4fuvFraaw', wiki: '鄭怡' },
  { slug: 'michelle-pan', group: 'female', name: '潘越雲', en: 'Michelle Pan', debut: '1979-10', channelId: 'UCCaauu_jc2rhNsx66SYjTKQ', wiki: '潘越雲' },
  { slug: 'jody-chiang', group: 'female', name: '江蕙', en: 'Jody Chiang', debut: '1981-04', channelId: 'UCJHd5tIDLb6YuNg3L_Ad15A', wiki: '江蕙' },
  { slug: 'chyi-chin', group: 'male', name: '齊秦', en: 'Chyi Chin', debut: '1981', channelId: 'UCXAFPuHD3vHw9agvXeY948A', wiki: '齊秦' },
  { slug: 'anita-mui', group: 'female', name: '梅艷芳', en: 'Anita Mui', debut: '1982', channelId: 'UCllyCYlWEeBeZ4v3kNqz0AA', wiki: '梅艷芳' },
  { slug: 'julie-sue', group: 'female', name: '蘇芮', en: 'Julie Sue', debut: '1983', channelId: 'UC7GaEq4YeIndQAmWZGCp1jA', wiki: '蘇芮', aliases: ['Julie Su'] },
  { slug: 'stella-chang', group: 'female', name: '張清芳', en: 'Stella Chang', debut: '1984', channelId: 'UCgqKZd77uZDWKtZYViztZng', wiki: '張清芳' },
  { slug: 'sandy-lam', group: 'female', name: '林憶蓮', en: 'Sandy Lam', debut: '1985', channelId: 'UChwNyOQOnJ6n1H5EDnkpXhw', wiki: '林憶蓮' },
  { slug: 'jacky-cheung', group: 'male', name: '張學友', en: 'Jacky Cheung', debut: '1985-04', channelId: 'UCSdxcm9HfRCubJBhW92QoFQ', wiki: '張學友' },
  { slug: 'andy-lau', group: 'male', name: '劉德華', en: 'Andy Lau', debut: '1985', channelId: 'UCoyRETheGZlMXL-Jx83UsHQ', wiki: '劉德華' },
  { slug: 'winnie-hsin', group: 'female', name: '辛曉琪', en: 'Winnie Hsin', debut: '1986', channelId: 'UCmC8dCKfO3ZZtxYNvkadmxA', wiki: '辛曉琪' },
  { slug: 'huang-yee-ling', group: 'female', name: '黃乙玲', en: 'Huang Yee-ling', debut: '1987', channelId: 'UCvAECH-laxIYOFxLmeRjcjA', wiki: '黃乙玲' },
  { slug: 'cyndi-chao', group: 'female', name: '趙詠華', en: 'Cyndi Chao', debut: '1988', channelId: 'UCSCwNNMlx6buDMAvK4K6PGA', wiki: '趙詠華', aliases: ['Cyndi Zhao'] },
  { slug: 'na-ying', group: 'female', name: '那英', en: 'Na Ying', debut: '1988', channelId: 'UC7tVAVl0FfQ4ylidGciMJZQ', wiki: '那英' },
  { slug: 'jeff-chang', group: 'male', name: '張信哲', en: 'Jeff Chang', debut: '1988', channelId: 'UC37Uu5Sk6MCBFJNSDPNbZ5w', wiki: '張信哲' },
  { slug: 'bobby-chen', group: 'male', name: '陳昇', en: 'Bobby Chen', debut: '1988', channelId: 'UC4lfQ2v3iBxHmYzYRKURyOQ', wiki: '陳昇' },
  { slug: 'faye-wong', group: 'female', name: '王菲', en: 'Faye Wong', debut: '1989', channelId: 'UCnAmvOfJxmcMd5q48BEIuPQ', wiki: '王菲', aliases: ['王靖雯', 'Shirley Wong'] },
  { slug: 'kuo-heng-chi', group: 'male', name: '郭子', en: 'Kuo Heng-Chi', debut: '1989', channelId: 'UCAPSacD-z0BrzC4ib6aoq3w', extraChannelIds: ['UCJvKttuOdmo0ribnORxfNwg', 'UC4ZZgiyCT6Bm2ZIYfUqVVnA'], wiki: '郭蘅祈' },
  { slug: 'william-so', group: 'male', name: '蘇永康', en: 'William So', debut: '1989', channelId: 'UC2R81DoE9-OQCb38YpeimZw', wiki: '蘇永康' },
  { slug: 'wan-fang', group: 'female', name: '萬芳', en: 'Wan Fang', debut: '1990', channelId: 'UC7W9UR7f56ZcmN-fGg4Pvww', wiki: '萬芳' },
  { slug: 'tarcy-su', group: 'female', name: '蘇慧倫', en: 'Tarcy Su', debut: '1990-03', channelId: 'UCuzREF7riRhr2BWRqEBcjBA', wiki: '蘇慧倫' },
  { slug: 'tiger-huang', group: 'female', name: '黃小琥', en: 'Tiger Huang', debut: '1990-08', channelId: 'UCV6FKRsG3xal52heBj_XWkA', wiki: '黃小琥' },
  { slug: 'sammi-cheng', group: 'female', name: '鄭秀文', en: 'Sammi Cheng', debut: '1990', channelId: 'UCM8Xiz5yxDCdsP_o6ihVcaA', wiki: '鄭秀文' },
  { slug: 'leon-lai', group: 'male', name: '黎明', en: 'Leon Lai', debut: '1990', channelId: 'UCH5hUc-wpv63XKUOEWziVWQ', wiki: '黎明' },
  { slug: 'aaron-kwok', group: 'male', name: '郭富城', en: 'Aaron Kwok', debut: '1990', channelId: 'UCRKMiqk5_omDtmZvWUQFxGQ', wiki: '郭富城' },
  { slug: 'karen-mok', group: 'female', name: '莫文蔚', en: 'Karen Mok', debut: '1993', channelId: 'UChrwddvlCf1df9skygWPA6g', wiki: '莫文蔚' },
  { slug: 'mavis-hee', group: 'female', name: '許美靜', en: 'Mavis Hee', debut: '1994', channelId: 'UCHl4oR3WDrHi49L2M6m33MA', wiki: '許美靜' },
  { slug: 'coco-lee', group: 'female', name: '李玟', en: 'CoCo Lee', debut: '1994-06', channelId: 'UCVzDS3qH_E2ooA7AimOrzHQ', wiki: '李玟' },
  { slug: 'valen-hsu', group: 'female', name: '許茹芸', en: 'Valen Hsu', debut: '1995-06', channelId: 'UCZgpCUQ69DOR8OUKAxD8exw', wiki: '許茹芸' },
  { slug: 'rene-liu', group: 'female', name: '劉若英', en: 'Rene Liu', debut: '1995', channelId: 'UCWY-I1axwr3X9YiouSwHf5Q', wiki: '劉若英' },
  { slug: 'mavis-fan', group: 'female', name: '范曉萱', en: 'Mavis Fan', debut: '1995', channelId: 'UCpCPwuMLFLFAWdHE3RWFjqg', wiki: '范曉萱' },
  { slug: 'leehom-wang', group: 'male', name: '王力宏', en: 'Wang Leehom', debut: '1995', channelId: 'UCSirtpIlKNCvnrTN4i0GFvw', wiki: '王力宏', aliases: ['Leehom Wang'] },
  { slug: 'eason-chan', group: 'male', name: '陳奕迅', en: 'Eason Chan', debut: '1995', channelId: 'UC2rCynaFhWz7MeRoqJLvcow', wiki: '陳奕迅' },
  { slug: 'michael-wong', group: 'male', name: '光良', en: 'Michael Wong', debut: '1995', channelId: 'UCSuMl2pt6TsRXo2p0eGmC5g', wiki: '光良' },
  { slug: 'victor-wong', group: 'male', name: '品冠', en: 'Victor Wong', debut: '1995', channelId: 'UCZwxvbsLquj9TE0GxLbAXlw', wiki: '品冠' },
  { slug: 'julia-peng', group: 'female', name: '彭佳慧', en: 'Julia Peng', debut: '1996', channelId: 'UC1tBiwuyXgWNLWiUpx53TRA', wiki: '彭佳慧' },
  { slug: 'gigi-leung', group: 'female', name: '梁詠琪', en: 'Gigi Leung', debut: '1996', channelId: 'UC_yk6-0jRw__Ys5cakYotcg', wiki: '梁詠琪' },
  { slug: 'shunza', group: 'female', name: '順子', en: 'Shunza', debut: '1996-11', channelId: 'UC-Cgo2VEj08oCVpbA2ME_IQ', wiki: '順子' },
  { slug: 'a-mei', group: 'female', name: '張惠妹', en: 'A-Mei', debut: '1996-12', channelId: 'UC5M7vIbPTCOMVF3lTtbeO6g', wiki: '張惠妹', aliases: ['Chang Hui Mei', 'aMEI', '阿密特'] },
  { slug: 'tanya-chua', group: 'female', name: '蔡健雅', en: 'Tanya Chua', debut: '1997', channelId: 'UCKbk-Nog0Sac_NHWntf3RHQ', wiki: '蔡健雅' },
  { slug: 'faith-yang', group: 'female', name: '楊乃文', en: 'Faith Yang', debut: '1997-07', channelId: 'UCvgxezGnDGWaQf8RLO46ljQ', wiki: '楊乃文' },
  { slug: 'panda-hsiung', group: 'male', name: '熊天平', en: 'Panda Hsiung', debut: '1997', channelId: 'UC7_HyHd-8qMYqUQ3r5TJA7w', wiki: '熊天平' },
  { slug: 'cheer-chen', group: 'female', name: '陳綺貞', en: 'Cheer Chen', debut: '1998-07', channelId: 'UC3Sf91aR21dEBHWwOxzXCRw', wiki: '陳綺貞' },
  { slug: 'jolin-tsai', group: 'female', name: '蔡依林', en: 'Jolin Tsai', debut: '1999-09-10', channelId: 'UC9dLsF7Ss7Wg0kR6TiIWiXg', wiki: '蔡依林' },
  { slug: 'fish-leong', group: 'female', name: '梁靜茹', en: 'Fish Leong', debut: '1999-09-17', channelId: 'UC8viexI7VBM6p632pCfTWRg', wiki: '梁靜茹' },
  { slug: 'elva-hsiao', group: 'female', name: '蕭亞軒', en: 'Elva Hsiao', debut: '1999-11', channelId: 'UCChWNfpWW8dUMmkgSWgOHKw', wiki: '蕭亞軒' },
  { slug: 'mayday', group: 'group', name: '五月天', en: 'Mayday', debut: '1999-07', channelId: 'UCQyweuVOAh3NHGKDDadRSbg', wiki: '五月天' },
  { slug: 'penny-tai', group: 'female', name: '戴佩妮', en: 'Penny Tai', debut: '2000', channelId: 'UCwdCmULcaKruVB5XMxT3gLg', wiki: '戴佩妮' },
  { slug: 'rainie-yang', group: 'female', name: '楊丞琳', en: 'Rainie Yang', debut: '2000', channelId: 'UC0WDze0vAMrLxULTWMlSuRA', wiki: '楊丞琳', aliases: ['4 In Love'] },
  { slug: 'christine-fan', group: 'female', name: '范瑋琪', en: 'Christine Fan', debut: '2000-11', channelId: 'UC49ijorxlIXpZRAC6wEQYWQ', wiki: '范瑋琪' },
  { slug: 'fire-ex', group: 'group', name: '滅火器', en: 'Fire EX.', debut: '2000', channelId: 'UCcny0_3Z2DtcCEYayEcgtPg', wiki: '滅火器樂團' },
  { slug: 'kenji-wu', group: 'male', name: '吳克群', en: 'Kenji Wu', debut: '2000-11', channelId: 'UCkf2xPKEIy78LVKZ4GOFIVA', wiki: '吳克群' },
  { slug: 'hebe-tien', group: 'female', name: '田馥甄', en: 'Hebe Tien', debut: '2001-09', channelId: 'UCGkj4uoWx_1BA2tF9Q-9Y6w', wiki: '田馥甄' },
  { slug: 'she', group: 'group', name: 'S.H.E', en: '', debut: '2001-09', channelId: 'UCGH6l-Hozjs8vSW83e4u-Gw', wiki: 'S.H.E', aliases: ['任家萱', 'Selina', '田馥甄', 'Hebe', '陳嘉樺', 'Ella'] },
  { slug: 'angela-chang', group: 'female', name: '張韶涵', en: 'Angela Chang', debut: '2002', channelId: 'UCKeK5Xj-iCfLOZvMDm3aIkw', wiki: '張韶涵' },
  { slug: 'shin', group: 'male', name: '信', en: 'Shin', debut: '2002-05', channelId: 'UCLffjF3BWiyHVDgrKfIh4SA', wiki: '信 (歌手)', aliases: ['蘇見信'] },
  { slug: 'waa-wei', group: 'female', name: '魏如萱', en: 'Waa Wei', debut: '2003', channelId: 'UCYul_G85M2ySouSZlqX_ipg', wiki: '魏如萱' },
  { slug: 'cyndi-wang', group: 'female', name: '王心凌', en: 'Cyndi Wang', debut: '2003', channelId: 'UC-GYedjoXTj4tj8IOMZbp9g', wiki: '王心凌' },
  { slug: 'jj-lin', group: 'male', name: '林俊傑', en: 'JJ Lin', debut: '2003-04', channelId: 'UCUJ3KuIIgvh8eVItvb-EdFQ', wiki: '林俊傑' },
  { slug: 'a-lin', group: 'female', name: 'A-Lin', en: '黃麗玲', debut: '2006', channelId: 'UCh8MAQTB0y4JMTROjINKenA', wiki: 'A-Lin', aliases: ['黃麗玲'] },
  { slug: 'jam-hsiao', group: 'male', name: '蕭敬騰', en: 'Jam Hsiao', debut: '2008', channelId: 'UCvjGf4upqUNaqi524A5AHIw', wiki: '蕭敬騰' },
  { slug: 'lala-hsu', group: 'female', name: '徐佳瑩', en: 'LaLa Hsu', debut: '2009', channelId: 'UC974iWoR_ZhWT6cNbZSaEdg', wiki: '徐佳瑩' },
  { slug: 'eve-ai', group: 'female', name: '艾怡良', en: 'Eve Ai', debut: '2010', channelId: 'UC_igPX3c9gOMQ41hSDV8tNg', wiki: '艾怡良' },
  { slug: '9m88', group: 'female', name: '9m88', en: '', debut: '2016', channelId: 'UCpZvDKDJtQUXm1o6LKT2xhA', wiki: '9m88' },
  { slug: 'for-what', group: 'group', name: '浮花樂隊', en: 'For What', debut: '2022', channelId: 'UCry9S-7wth479tbrtiP_l9A', wiki: null },
]

export const GROUPS = [
  { key: 'female', label: '女歌手', title: '天后', unit: '位' },
  { key: 'male', label: '男歌手', title: '天王', unit: '位' },
  { key: 'group', label: '團體', title: '團體', unit: '組' },
]

export const artistsIn = (group) => ARTISTS.filter((a) => a.group === group)

export const findArtist = (slug) => ARTISTS.find((a) => a.slug === slug)
